### ISSUE TITLE
ClassfileManager crashes when name hashing is enabled

### ISSUE THREAD

**Issue by gkossakowski** [sbt/sbt#1184]
@aloiscochard reported on sbt-dev a crash in ClassfileManager when name hashing is enabled:

```
java.lang.IllegalArgumentException: requirement failed: Source file '/home/alois/timeout/jvm/target/classes.bak/sbt3697008749647665633.class' does not exist.
        at scala.Predef$.require(Predef.scala:233)
        at sbt.IO$.copyFile(IO.scala:580)
        at sbt.IO$.move(IO.scala:764)
        at sbt.inc.ClassfileManager$$anonfun$transactional$1$$anon$2$$anonfun$complete$2.apply(ClassfileManager.scala:53)
        at sbt.inc.ClassfileManager$$anonfun$transactional$1$$anon$2$$anonfun$complete$2.apply(ClassfileManager.scala:53)
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
        at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
        at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
        at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:226)
        at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:39)
        at scala.collection.mutable.HashMap.foreach(HashMap.scala:98)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771)
        at sbt.inc.ClassfileManager$$anonfun$transactional$1$$anon$2.complete(ClassfileManager.scala:53)
        at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:66)
        at sbt.inc.Incremental$.compile(Incremental.scala:37)
```

The full compilation log is available here: http://pastie.org/8916318

Unfortunately, we don't log activity of ClassfileManager so it's hard to tell why the class file is missing. Also, we do not log the name of the class the ClassfileManager tried to restore. It's hard to tell whether it was the last compilation iteration or earlier compilation that caused removal of the class file.

**Comment by aloiscochard** [comment]
@gkossakowski next time it would be nice if you could update that ticket if you expect me to do an action (like giving more debug information).

I'm not following sbt itself but just that ticket, so there was no way I would have guess you did that change without -by random chance- got notified on twitter.

If you write a message on that ticket, or on that forum thread:
https://groups.google.com/d/msg/sbt-dev/KmGEhFTMve0/pyyMVeg4QNgJ

I'll be notified :-)

I'm enabling name hashing now and let you know how it goes.

**Comment by aloiscochard** [comment]
_In fact it a bit of a shame Github don't notify when the PR is referenced somewhere else :-(_

**Comment by gkossakowski** [comment]
@aloiscochard: good point on notifying you! I'll keep this in mind. I agree it would be great if GitHub notified automatically in case PR is merged that mentions given ticket.

I'm looking forward to your findings!

**Comment by aloiscochard** [comment]
@gkossakowski I tried to enable with 0.13.5-M3 but it looks like this change was not in it.

So I tried to use the sbt nightly (0.13.5-20140412-061917), but then why I start SBT he don't find any dependencies for my plugins.

Could you guys release a milestone with the change? or give me instruction about how to actually use a sbt version which include that change?

For information here is the error I got form 0.13.5-M3:

```
[info] Compiling 1 Scala source to /home/alois/timeout/jvm/project/target/scala-2.10/sbt-0.13/classes...
[error] /home/alois/timeout/jvm/project/TimeOutBuild.scala:35: too many arguments for method transactional: (tempDir0: java.io.File)() => sbt.inc.ClassfileManager
```

I would be happy to help (as long as I don't have to hack sbt code ;) ), but I actually don't see how I can.

**Comment by aloiscochard** [comment]
FYI, when trying to use the snapshot I got:
`sbt.ResolveException: unresolved dependency: com.typesafe.sbteclipse#sbteclipse-plugin;2.4.0: not found`

Which is pretty weird as it should be able to use the same version of the plugin (it's still 0.13)

**Comment by jsuereth** [comment]
@aloiscochard can you give us more information on what Ivy says prior to that error?

Also, the CI server has been hosed for a while, so I'm not sure when the last nightly was, but I haven't been able to get it to kick out the current one for a few days.

**Comment by aloiscochard** [comment]
@jsuereth here is the full SBT output http://pastie.org/9085063

**Comment by jsuereth** [comment]
Ah, yay.  This is an issue with the binary version detector and the way sbt does SNAPSHOTs in ivy.

See this line:

```
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.typesafe.sbteclipse:sbteclipse-plugin:2.4.0 (scalaVersion=2.10, sbtVersion=0.13.5-20140412-061917)
```

The detector doesn't take -<date>-<number> as a valid `-SNAPSHOT` right now.  cc> @eed3si9n.   This _does_ work for publishLocal -SNAPSHOT builds, but not how we publish snapshots to our artifactory.

Can you open a ticket about that specifically?  Thanks

**Comment by gkossakowski** [comment]
@jsuereth: is there a plan for 0.13.5-M4 release? I'd love to get debugging info from @aloiscochard.

@aloiscochard: as an alternative, would it be possible for you to checkout sbt and run `publishLocal` yourself? It seems like this would allow you to use SNAPSHOT version of sbt and resolve the plugins correctly.

**Comment by jsuereth** [comment]
@gkossakowski We're due for one tomorrow actually, as well as next thursday.  Two more before the final RC.  Note:  Feature freeze is next friday, and i don't plan to work anything but bug fixes and docs next week.

**Comment by aloiscochard** [comment]
@gkossakowski sure, that's fine by me!

I'll give it a try tomorrow morning and let you know how it goes (hopefully if I find time). Worst case next week.

**Comment by aloiscochard** [comment]
@gkossakowski here is the result of the last run:
http://pastie.org/9104792

I don't see any more information (having enabled https://github.com/sbt/sbt/pull/1254) I tried to find something in target, but I don't see what you guys added.. it's not like I know my target that well.

So I just archive the whole target and put it here:
https://dl.dropboxusercontent.com/u/7165324/target.tar.gz

Do you see the information you were expecting to see @gkossakowski ?

**Comment by gkossakowski** [comment]
@aloiscochard: no, I think the logs got blackholed because you did `streams in Compile`.

This works for me:

``` scala
incOptions := incOptions.value.withNewClassfileManager(
  sbt.inc.ClassfileManager.transactional(
    crossTarget.value / "classes.bak",
    (streams in (Compile, compile)).value.log
  )
)
```

with that, I see:

```
[debug] Sources indirectly invalidated by:
[debug]     product: Set(/Users/grek/tmp/sbt-name-hashing/Foo.scala, /Users/grek/tmp/sbt-name-hashing/Abc.scala, /Users/grek/tmp/sbt-name-hashing/Bar.scala)
[debug]     binary dep: Set()
[debug]     external source: Set()
[debug] All initially invalidated sources: Set(/Users/grek/tmp/sbt-name-hashing/Foo.scala, /Users/grek/tmp/sbt-name-hashing/Abc.scala, /Users/grek/tmp/sbt-name-hashing/Bar.scala)
[debug] Created transactional ClassfileManager with tempDir = /Users/grek/tmp/sbt-name-hashing/target/scala-2.10/classes.bak
```

The last line is coming from logging of ClassfileManager. You should see something similar.

**Comment by aloiscochard** [comment]
So I added this:

```
    incOptions := incOptions.value.withNewClassfileManager(
      sbt.inc.ClassfileManager.transactional(
        crossTarget.value / "classes.bak",
        (streams in (Compile, compile)).value.log
      )
    ),
```

and that's all I have:
http://pastie.org/9108317

@gkossakowski do I miss something or the information you mentioned are not there?

**Comment by aloiscochard** [comment]
@gkossakowski @jsuereth any news on this?

**Comment by gkossakowski** [comment]
Hi @aloiscochard! The log you posted doesn't include output from ClassfileManager :-/
I'm wondering whether your build is a multi-project build and you configure logging for some other subproject from the one that crashes?

**Comment by aloiscochard** [comment]
Yes @gkossakowski now that you mention it, I'm sure that's the issue!!

I'll give it an other try tomorrow and **this time** I'll give you proper log :-)

**Comment by gkossakowski** [comment]
@aloiscochard: did you have a chance to gather the log output?

**Comment by aloiscochard** [comment]
@gkossakowski I gave it a try last week but I'm not sure how I messed with the configuration... I think it didn't got enabled at the end.

I was actually thinking about it today, I'm sorry I haven't spend more time on it... but I will next week!

**Comment by gkossakowski** [comment]
No worries. I've seen @paulp has run into this as well: https://twitter.com/extempore2/status/464826207515602944

We'll see which one of you will be the first to shed more light on this issue.

**Comment by aloiscochard** [comment]
I heard from others, that anyone one try to seriously use name hashing and switch branches often have this issue.

**Comment by gkossakowski** [comment]
Sbt is using name hashing now and we haven't experienced this issue. The
same goes for Akka.

Is this issue easily reproducible on any code base?

W dniu wtorek, 8 lipca 2014 Alois Cochard notifications@github.com
napisał(a):

> I heard from others, that anyone one try to seriously use name hashing and
> switch branches often have this issue.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sbt/sbt/issues/1184#issuecomment-48323836.

## 

Grzegorz Kossakowski
Scalac hacker at Typesafe http://www.typesafe.com/
twitter: @gkossakowski http://twitter.com/gkossakowski
github: @gkossakowski http://github.com/gkossakowski

**Comment by aloiscochard** [comment]
That's crazy! I never heard anyone that tried it and didn't had this issue...

I'll give it an other try on our codebase and let you know.

Since which version is that active by default?

**Comment by gkossakowski** [comment]
Thanks. I'd really love to nail down this issue.

It's not active by default but build for sbt itself and Akka enabled this
option around two months ago.

W dniu wtorek, 8 lipca 2014 Alois Cochard notifications@github.com
napisał(a):

> That's crazy! I never heard anyone that tried it and didn't had this
> issue...
> 
> I'll give it an other try on our codebase and let you know.
> 
> Since which version is that active by default?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sbt/sbt/issues/1184#issuecomment-48354338.

## 

Grzegorz Kossakowski
Scalac hacker at Typesafe http://www.typesafe.com/
twitter: @gkossakowski http://twitter.com/gkossakowski
github: @gkossakowski http://github.com/gkossakowski

**Comment by aloiscochard** [comment]
@gkossakowski Hi Greg,

I have an intuition... a very strong one about this bug... just let me give a bit of context.

For quite a while, my sbt was suboptimal when it comes to using it with `~` or having on running continuously and an other one with `run`.

Today, while ranting about it one of my coworker show me it's not the same for him... so I started investigation.

I was using this script:
https://github.com/paulp/sbt-extras

Which I now have stopped using, and everything is going much smoother!

I think that explain why few folks had the issue, while I had the feeling it was fundamental one... anyway I renable name-hashing and let you know... but I thought it was worth sharing that first guess with you.

**Comment by gkossakowski** [comment]
Thanks for sharing! That sheds some light on why I couldn't reproduce this issue.

@jsuereth do you have any idea how sbt-extras could interfere here?

**Comment by paulp** [comment]
It will show you exactly what it's doing. If it is really something in my script it should be immediately apparent. Here is the java command line which it issues by default.

```
% sbt -v
No extra sbt options have been defined
Detected sbt version 0.13.5
Starting sbt: invoke with -help for other options
Using default jvm options
# Executing command line:
/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/bin/java
-XX:MaxPermSize=384m
-Xms512m
-Xmx1536m
-Xss2m
-XX:ReservedCodeCacheSize=256m
-XX:+TieredCompilation
-XX:+CMSClassUnloadingEnabled
-XX:+UseConcMarkSweepGC
-jar
/Users/paulp/.sbt/launchers/0.13.5/sbt-launch.jar
shell
```

**Comment by paulp** [comment]
@aloiscochard mentions using ~ and then using run in another window. That is exactly the circumstance I was talking about earlier when I speculated about competing sbt invocations running into one another. I can tell you for sure you will encounter bad things if you use "sbt run" while continuous compilation is going in another window, unless the continuous compilation is all caught up and therefore quiescent. But that would be exactly as true without my runner. Unless the alternative is not invoking java directly but some runner I don't know about which performs some coordination.

**Comment by paulp** [comment]
An easy step which could be taken by sbt would be to either lock the output directory for classfile emission or to check if the classfile directories being written to have been written to by something else in the extremely recent past and responding with anything more sane than randomly interleaving filesystem operations (choices include issuing a warning, aborting and not writing at all, backing off until the directory isn't actively undergoing modification, etc.)

**Comment by ijuma** [comment]
By the way, I (aka @aloiscochard's coworker) don't run multiple SBT instances concurrently so @paulp may well be right.

**Comment by aloiscochard** [comment]
You are totally right Paul.

Few hours after switching to using directly sbt the issue was back :-(

Sorry for having doubted about your very useful script!

**Comment by aloiscochard** [comment]
@paulp BTW, I'm curious how do you organize your flow to work around the issue (of having one sbt with ~ and then other to run `main`), for me it's really a productivity killer... any idea?

**Comment by paulp** [comment]
Sorry, it's a problem for me too. I don't know how to deal with it. I'd love to see it addressed in sbt.

**Comment by paulp** [comment]
> Sorry for having doubted about your very useful script!

Don't worry, blaming sbt-extras when the problem is unclear is a national pastime.

**Comment by gkossakowski** [comment]
@aloiscochard, are you running just one instance at the time and still see this problem?

Could enable logging of ClassfileManager activity?

**Comment by aloiscochard** [comment]
@gkossakowski nope, I haven't retried yet. I wanted to be sure to understand the issue with `update` first.

I'll let you know when I have any news.

**Comment by aloiscochard** [comment]
@paulp Just for your information, I just found a "workaround" for my workflow by using https://github.com/spray/sbt-revolver with `~;test:testOnly *FooTest*; re-start`, but that solve probably only my very specific use-case... anyway I thought it might be worth sharing ;-)

@gkossakowski with that new setup in place, I'll finally re-enable name hashing and keep you posted

**Comment by aloiscochard** [comment]
@gkossakowski one day without issue (but haven't changed branches much), I'll give you feedback at the end of the week.... but so far so good! :)

**Comment by gkossakowski** [comment]
Thanks for keeping us updated! Keeping fingers crossed for you testing!

**Comment by paulp** [comment]
In case people are being overly distracted by specifics, there's clearly a real issue here for which there are no general workarounds, and that is write synchronization. Only sbt can adequately address it. The way sbt works basically any action can lead to compilation, so there are highly unintuitive combinations where you will incur utterly random behavior: let's say we run two copies of a program, and then something simply touches a source file without changing it. Recompilation race ensues, classfiles are lost, ClassNotFound or worse, all without cause.

Lock the output directory when you're writing to it. Nothing good can come of concurrently writing to the same location from multiple processes.

**Comment by jsuereth** [comment]
@paulp That is a very serious issue, one which we'd like to solve in a bit more nuanced way than "global lock on anything writing to target, across processes" which is how we "solved" ivy process concurrency issues.

Primarily, in sbt 1.0 (next major release), sbt-server will be the default mode of operation, which means all clients will actually connect to one build process, who will own the lock to a project directory.  This is merely a band-aid around the fundamental issues of using a filesystem.

I think, we'll have to look into a more robust solution in the future as well, possibly inherent in how you define tasks which generate files.

@gkossakowski for the 0.13 series, we could possibly "lock" on the analysis object in the compilation task.... You can look at how we do that for the update task as an example.   WDYT?

**Comment by paulp** [comment]
For the record I'm not arguing for something lacking nuance in preference to something possessing nuance, but I am arguing for something as contrasted with nothing. It's easy enough to mitigate the problem that a desire for nuance is not really a reason to delay so doing. 1.0 sounds really far away compared to the quantity of attention requisite.

**Comment by aloiscochard** [comment]
@gkossakowski I just got a crash, but I think it's not the _same_ issue as I was facing in the past, here is the bug report:
https://github.com/sbt/sbt/issues/1479

Hope that help!

**Comment by gkossakowski** [comment]
I created a separate issue for tracking the problem of incremental compiler not being multiprocess safe, see #1522.

I'm closing this one with resolution that's not a bug in incremental compiler or name hashing specifically.
