### ISSUE TITLE
Cross compiling for dependsOn

### ISSUE THREAD

**Issue by huntc** [sbt/sbt#1448]
@eed3si9n rewrote this case.
## steps

```
$ cat project/build.properties 
sbt.version=0.13.5
```

``` scala
$ cat build.sbt               
lazy val rootProj = (project in file(".")).
  aggregate(fooProj, barProj).
  settings(
    scalaVersion := "2.11.1",
    crossScalaVersions := Seq("2.10.4", "2.11.1")
  )

lazy val fooProj = (project in file("foo")).
  dependsOn(barProj).
  settings(
    scalaVersion := "2.10.4"
  )

lazy val barProj = (project in file("bar")).
  settings(
    scalaVersion := "2.11.1",
    crossScalaVersions := Seq("2.10.4", "2.11.1")
  )
```
## problem

```
$ sbt compile
[info] Loading global plugins from /Users/eugene/dotfiles/sbt/0.13/plugins
[info] Loading project definition from /Users/eugene/work/quick-test/sbt-1448/project
[info] Set current project to rootProj (in build file:/Users/eugene/work/quick-test/sbt-1448/)
[info] Updating {file:/Users/eugene/work/quick-test/sbt-1448/}fooProj...
[info] Resolving barproj#barproj_2.10;0.1-SNAPSHOT ...
[warn]  module not found: barproj#barproj_2.10;0.1-SNAPSHOT
[warn] ==== local: tried
[warn]   /Users/eugene/.ivy2/local/barproj/barproj_2.10/0.1-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/barproj/barproj_2.10/0.1-SNAPSHOT/barproj_2.10-0.1-SNAPSHOT.pom
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: barproj#barproj_2.10;0.1-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: unresolved dependency: barproj#barproj_2.10;0.1-SNAPSHOT: not found
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:217)
    at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:126)
    at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:125)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:115)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:115)
    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:103)
    at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:48)
    at sbt.IvySbt$$anon$3.call(Ivy.scala:57)
```
## expectation
1. `fooProj` is either excluded from aggregation
2. or `scalaVersion` is switched to "2.10.4" when it runs `compile` task under `fooProj`.
## original report

When using

```
lazy val a = project
lazy val b = project dependsOn a
```

...where project a is Scala version x and project b is Scala version y

...then the class path of a in the context of b should be for Scala version y i.e. b's Scala version.

**Comment by eed3si9n** [comment]
Here's a workaround:

``` scala
lazy val rootProj = (project in file(".")).
  aggregate(fooProj, barProj).
  settings(
    scalaVersion := "2.11.1",
    crossScalaVersions := Seq("2.10.4", "2.11.1")
  ).settings(
    addCommandAlias("muchCompile", ";++2.11.1;barProj/compile;++2.10.4;fooProj/compile"): _*
  )
```

**Comment by huntc** [comment]
The point is though I want it automated and not have to invoke a new task... Am I missing something?

**Comment by eed3si9n** [comment]
No you're right on the money. I hope I captured your expectation in the description part of the case.

Personally, I've been thinking `+compile` _should_ work as `muchCompile`. But since that would require a new version of sbt, a temporary workaround that's relatively non-invasive is the above workaround.

**Comment by xuwei-k** [comment]
+1

**Comment by eed3si9n** [comment]
Here's a plugin that I wrote to prototype better "+" - https://github.com/sbt/sbt-doge.

**Comment by EECOLOR** [comment]
Awesome! The plugin works very well. My brain tripped on the dog and `very` `much` `so` `such`, but I soon realized I could add another alias:

``` scala
commands += sbtdoge.Doge.crossBuildCommand("fixed+")
```

**Comment by joan38** [comment]
Is there any fix scheduled for that?

**Comment by iaraknes** [comment]
+1

**Comment by angelcervera** [comment]
Any intention to fix it? 3 years and still open.

**Comment by eed3si9n** [comment]
This should be fixed in sbt 1 since it incorporates doge.

**Comment by fchaillou** [comment]
Actually, this still doesn't work.
I tried with sbt 1.1.6 and sbt still tries to fetch the barProj with ivy instead of using the local project ref as it should

**Comment by fchaillou** [comment]
To complete my previous answer, it works and doesn't work at the same time (the shroedinger build :D)
So if i run `+fooProj/compile` then it works as expected but if i try to run `+compile` then it still fails as described in this bug
