### ISSUE TITLE
[0.13.7-RC2] cached resolution pulls in % "test" dependencies from other subproj

### ISSUE THREAD

**Issue by japgolly** [sbt/sbt#1711]
From: https://groups.google.com/forum/#!folder/Scala/sbt-dev/k4XZiKQjVHA

There seems to be one issue: it generates a different dependency tree for (at least) one of my modules. Noticeable because I now see deprecation warnings from the new version of the library which isn't supposed to be on my classpath and isn't with 0.13.6. Here is some data for said module, let's call it module A.
https://gist.github.com/japgolly/149ad9a9491a3515abca

Three problems are evident here.
1. I'm explicitly declaring 1.11.3 of ScalaCheck in my build but 1.11.4 is used.
2. This module dependsOn module B. Module B uses utest as a test dependency. I'm now see utest.jar on module A's test classpath.
3. Way more specs2 jars on the classpath. I'm explicitly only depending on -core and -scalacheck.

(By the way, I can't run dependencyTree for comparison because it doesn't work on 0.13.6 for some reason. Keeps harping on about blah-compile.xml not found.)

**Comment by eed3si9n** [comment]
Thanks for the report. I'm guessing the first issue ScalaCheck bump up is happening because of the third issue of more specs2 jars, which is happening because of the second issue of % "test" getting pulled in.

**Comment by japgolly** [comment]
Nice work. I'll test this again with the next RC.

**Comment by eed3si9n** [comment]
I just released RC-3.

**Comment by japgolly** [comment]
I'm still getting failure, although of a different kind. I'll investigate and raise another ticket.

**Comment by eed3si9n** [comment]
sbt 0.13.8-M6 is out with another attempt of fix.
Could you see if it works?

**Comment by japgolly** [comment]
This seems to be fixed with 0.13.8-M6. Good job! :)
