### ISSUE TITLE
Wrong sbt bin path added to PATH environment variable on Windows

### ISSUE THREAD

**Issue by RomainVernoux** [sbt/sbt#2240]
I installed sbt from the msi installer (`sbt-0.13.9.msi` from [http://www.scala-sbt.org/download.html](http://www.scala-sbt.org/download.html)) on a Windows 10 computer. I tried `sbt` in the Windows console but it was not a recognized command.

After looking in the `PATH` env variable I noticed that there was a typo: 
`C:\Program Files (x86)\sbt\\bin`
instead of 
`C:\Program Files (x86)\sbt\bin`

**Comment by muojp** [comment]
Reproduced on my machine w/ sbt-0.13.9.msi.

I searched a bit and found this issue(#2240) is a duplicate of #2023 which was already closed regarding root issue: https://github.com/sbt/sbt-launcher-package/issues/76

**Comment by alebaffa** [comment]
I had the same problem now installing sbt 0.13.12 on Windows 10. I didn't have this problem today, so the same day, on Windows 8. 
Is anyone taking care of this? It's open since 8 months now with no updates and the issue is still there.

**Comment by dwijnand** [comment]
Duplicate of https://github.com/sbt/sbt-launcher-package/issues/76

**Comment by eed3si9n** [comment]
Dale (@dwijnand) fixed the bug so I published a new installer for Windows for 0.13.12. Could you try using it, and see if it fixes the issue for you?
http://www.scala-sbt.org/download.html

**Comment by AmirMeirbekov** [comment]
I tried new installer and chose "Repair" option in launcher - it didn't fix the issue for me

**Comment by vdabravolski** [comment]
Reproduced on Windows 10.

**Comment by pw1z** [comment]
I see this was closed but 2021 now - downloaded sbt-1.5.5.msi for Windows 10 pro, still getting warning:
[warn] Neither build.sbt nor a 'project' directory in the current directory: ...

This is in my Environment Variables:
C:\Program Files (x86)\sbt\bin\
