### ISSUE TITLE
Missing filename from "java.io.IOException: destination file exists and overwrite == false" in sbt 1.0

### ISSUE THREAD

**Issue by olafurpg** [sbt/sbt#3431]
## steps
```
git clone https://github.com/lihaoyi/scalatex
cd scalatex
sbt +publishSigned
...
[info] 	published scalatex-site_2.11 to https://oss.sonatype.org/service/local/staging/deploy/maven2/com/lihaoyi/scalatex-site_2.11/0.3.10/scalatex-site_2.11-0.3.10-sources.jar
[error] java.io.IOException: destination file exists and overwrite == false
[error] 	at org.apache.ivy.plugins.repository.url.URLRepository.put(URLRepository.java:75)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$LocalIfFileRepo.put(ConvertResolver.scala:369)
[error] 	at org.apache.ivy.plugins.repository.AbstractRepository.put(AbstractRepository.java:130)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put(ConvertResolver.scala:121)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put$(ConvertResolver.scala:108)
[error]
```

## problem

The exception doesn't include the filename of the destination file.

## expectation

I expected the full path of the culprit file to appear in the exception message.

## notes

The build is using sbt 1.0.0

**Comment by olafurpg** [comment]
Culprit line seems to be https://github.com/sbt/librarymanagement/blob/e91e5c9e77f8850bd1f0689045d43d296ef8d66d/ivy/src/main/scala/sbt/internal/librarymanagement/ConvertResolver.scala#L370

**Comment by olafurpg** [comment]
Interestingly, the error happens even if I remove ~/.ivy/local, target and ~/.m2. I have no idea where this duplicate file exists.

**Comment by eed3si9n** [comment]
Do you have any files in the Sonatype Staging repo?

**Comment by olafurpg** [comment]
Good question, that sounds likely. Should overwrite be true if that's the case? It's kind of annoying to have to drop, open, and re-publishSigned all cross-built projects (~70 artifacts in scalameta/scalameta) in case Maven validation fails for a single artifact (e.g., missing javadoc). 

In my limited time with sbt 1.0, I've found the overwrite = false change to be quite painful for local development. I don't recall having experienced problems with overwrite=true in 0.13, besides the warning messages saying it will be removed in 1.0 causing me to miss other important messages in the console 😅  Is it possible to configure sbt 1.0 to use overwrite = true somewhere globally? Using -SNAPSHOT is not an option for large multi-module builds in my experience, resolution is too slow.

**Comment by leonardehrenfried** [comment]
@eed3si9n Would you merge in PR for this? The solution seems trivial.

**Comment by eaplatanios** [comment]
I have a similar issue where I have a `version.sbt` file containing `version in ThisBuild := "0.1.0-SNAPSHOT"` and `isSnapshot` is set to `true` when I check it's value on the console. However, I get the same error (`java.io.IOException: destination file exists and overwrite == false`) when I try to use `publishSigned`. For the publish settings, I also include:

```
  publishTo := Some(
    if (isSnapshot.value)
      Opts.resolver.sonatypeSnapshots
    else
      Opts.resolver.sonatypeStaging
  )
```

The only workaround I have found is to manually go on my snapshot repository online and remove the files. Is there some SBT option I can set to avoid that? Thank you! :)

**Comment by leonardehrenfried** [comment]
By the way, in our case the error was caused by a sub project that had the same name as the root folder. Setting 
```
publish := {}
publishLocal := {}
```
on the root project (disabling publishing) fixed this for us.

I'm hoping sbt 1.0.3 contains my fix linked to above. It gives you at least a chance a debugging this issue.

**Comment by eaplatanios** [comment]
@leonardehrenfried Thanks for the suggestion! In my case, I also publish artifacts for the root project and I also do not have any sub-projects with the same name as the root folder. This is unfortunately therefore not working for me.

Isn't there a simple way to allow overriding the "overwrite" flag?

**Comment by leonardehrenfried** [comment]
I think the overwrite flag isn't something a user can set but is used internally by SBT for snapshots.

Again, hopefully SBT 1.0.3 will help you to figure out which file is the problem.

**Comment by eaplatanios** [comment]
@leonardehrenfried Ok. In that case, I can wait for that change to go through and see if it helps although I feel that knowing the file that causes the issue will not really help in this case. It's just that even though me version ends with "-SNAPSHOT" and `isSnapshot` is set correctly, `overwrite` still seems to be `false` for some reason. And that only happens with SBT 1.0. With SBT 0.13 everything works fine.

**Comment by nrinaudo** [comment]
I'm having the exact same issue (1.0.x only, 0.13.x works fine) and the only work around I have is to delete pre-existing SNAPSHOT artifacts from sonatype.

**Comment by eed3si9n** [comment]
Fixed by https://github.com/sbt/sbt/pull/3674

**Comment by eaplatanios** [comment]
@eed3si9n I'm still getting the same error with version 1.0.3.

**Comment by dwijnand** [comment]
The error is expected. See the report:

> ## problem
> 
> The exception doesn't include the filename of the destination file.
> 
> ## expectation
> 
> I expected the full path of the culprit file to appear in the exception message.

**Comment by eaplatanios** [comment]
@dwijnand I'm sorry, you're right regarding the original posted issue. However, since the error is expected, how are we supposed to deal with the situation that me and @nrinaudo are describing? Currently, whenever I want to update snapshot releases, I have to go to Sonatype and delete any pre-existing snapshot artifacts.

**Comment by eaplatanios** [comment]
@dwijnand FYI, my current temporary solution is that I added a task defined as shown below to my project. This is not elegant thought and I would like to know what the recommended approach is, if there is one.

```scala
deletedPublishedSnapshots := {
    Process(
      "curl" :: "--request" :: "DELETE" :: "--write" :: "%{http_code} %{url_effective}\\n" ::
          "--user" :: s"${System.getenv().get("SONATYPE_USERNAME")}:${System.getenv().get("SONATYPE_PASSWORD")}" ::
          "--output" :: "/dev/null" :: "--silent" ::
          s"${Opts.resolver.sonatypeSnapshots.root}/${organization.value.replace(".", "/")}/" :: Nil) ! streams.value.log
  }
```

**Comment by maqdev** [comment]
Actually even the original bug isn't fixed. Proposed solution in https://github.com/sbt/librarymanagement/pull/171/files#diff-b37282394a4686fb706430bc4f82ad88R365 fixes this only for local publish `IO.FileScheme`.

In case when the problem is with Sonatype there is no file name in exception even with `1.0.3`.

**Comment by wsargent** [comment]
I'm still getting this in sbt v1.1.0 -- it looks like https://github.com/sbt/sbt/pull/3674 is for the 1.0.x branch only and did not get cross-PR to the 1.1.x branch.

EDIT: Nope, it is on the 1.1.x branch as well.  It must not be published yet https://github.com/sbt/librarymanagement/blob/1.1.x/ivy/src/main/scala/sbt/internal/librarymanagement/ConvertResolver.scala#L370

**Comment by wsargent** [comment]
For the record, the reason I was running into this was I set `crossScalaVersions` in a `CommonSettings` AutoPlugin, and then ran sbt-release.   It turns out that when you add `crossScalaVersions`, when you have a Java only project then `sbt-release` will always try to publish it twice, even if you set it to `Nil`, even if you set `releaseCrossBuild := false` in the Java project, etc.  Only way to stop double publishing is to remove `crossScalaVersions` as a setting applied to all projects.

**Comment by eed3si9n** [comment]
sbt 1.1.0 uses LM 1.1.2, which should include the patch:
https://github.com/sbt/librarymanagement/blob/v1.1.2/ivy/src/main/scala/sbt/internal/librarymanagement/ConvertResolver.scala#L370

**Comment by ffinfo** [comment]
Maybe a little update on this. I found out that in sbt-pgp the overwrite flag is hard coded. This why I did a PR to this plugin:
https://github.com/sbt/sbt-pgp/pull/121

**Comment by nogurenn** [comment]
@ffinfo Is it possible to introduce a patch into the sbt codebase instead? I checked the sbt-pgp repository and found an inactive/dead repository.

**Comment by ffinfo** [comment]
@nogurenn Not sure what you mean here. As far I know this plugin is not integrated inside sbt. Sbt itself does not support the command `publishSigned`, this is what this plugin does add.

**Comment by nogurenn** [comment]
@ffinfo That's weird. I was reading this thread because the exception is also raised when I try to do `sbt publish` toward my company's Nexus repository. This was my experience for both 0.13.7 and 1.x. It doesn't let me overwrite the artifact versions I already published (for testing).

**Comment by ffinfo** [comment]
@nogurenn Looks like there 2 separated issues then. The issue I did solved only affects `sbt publishSigned` so not `sbt publish` and only in sbt 1.x.

`sbt publish` is indeed something that should be fixed in the sbt codebase.

**Comment by eed3si9n** [comment]
If strict `overwrite == false` is causing actual issues, you might want to try something like this:

```scala
publishConfiguration := publishConfiguration.value.withOverwrite(true)
com.typesafe.sbt.pgp.PgpKeys.publishSignedConfiguration := com.typesafe.sbt.pgp.PgpKeys.publishSignedConfiguration.value.withOverwrite(true)
publishLocalConfiguration := publishLocalConfiguration.value.withOverwrite(true)
com.typesafe.sbt.pgp.PgpKeys.publishLocalSignedConfiguration := com.typesafe.sbt.pgp.PgpKeys.publishLocalSignedConfiguration.value.withOverwrite(true)
```

Adopted from https://github.com/sbt/sbt/issues/3725#issuecomment-368367908

**Comment by fommil** [comment]
the exception still doesn't contain the filename in 1.1.1, was this closed by accident?

**Comment by eed3si9n** [comment]
https://github.com/sbt/librarymanagement/pull/171 did add the error message here - https://github.com/sbt/librarymanagement/blob/v1.1.3/ivy/src/main/scala/sbt/internal/librarymanagement/ConvertResolver.scala#L369-L371

**Comment by Sciss** [comment]
Hello. I have this problem when running `+publishSigned` in a multi-project build where one out of six modules is not Scala and thus has `crossPaths := false` and `autoScalaLibrary := false`. What is the technique to avoid that sbt tries to write that one module twice (`crossScalaVersions` in project are 2.12, 2.11)? How can I set `overwrite == true`?

**Comment by ffinfo** [comment]
@Sciss First good to know that publishSigned is not a command of sbt itself but from the sbt-pgp plugin. See also: https://github.com/sbt/sbt-pgp
On there I recently did a PR request that is fixing your issue. For this you need sbt-pgp 1.1.1

**Comment by Sciss** [comment]
@ffinfo Ok great; sorry I wasn't aware that `publishSigned` is provided by third-party plugin.

**Comment by eed3si9n** [comment]
I wonder if what @fommil saw was the same sbt-pgp issue fixed in https://github.com/sbt/sbt-pgp/pull/121.

**Comment by fommil** [comment]
yup. I upgrade regularly https://gitlab.com/fommil/sbt-sensible/blob/master/build.sbt

**Comment by eed3si9n** [comment]
Does that mean I can close this issue?

**Comment by fommil** [comment]
I think so

**Comment by pathikrit** [comment]
I am getting same error even after doing

```
lazy val releaseSettings = Seq(
  // work around for https://github.com/sbt/sbt/issues/3431
  publishConfiguration := publishConfiguration.value.withOverwrite(true),
  com.typesafe.sbt.pgp.PgpKeys.publishSignedConfiguration := com.typesafe.sbt.pgp.PgpKeys.publishSignedConfiguration.value
    .withOverwrite(true),
  publishLocalConfiguration := publishLocalConfiguration.value.withOverwrite(true),
  com.typesafe.sbt.pgp.PgpKeys.publishLocalSignedConfiguration := com.typesafe.sbt.pgp.PgpKeys.publishLocalSignedConfiguration.value
    .withOverwrite(true),
  // end work around
  releaseProcess := Seq[ReleaseStep](
    checkSnapshotDependencies,
    inquireVersions,
    //runClean,
    runTest,
    setReleaseVersion,
    commitReleaseVersion,
    tagRelease,
    releaseStepCommand("publishSigned"),
    setNextVersion,
    commitNextVersion,
    releaseStepCommand("sonatypeReleaseAll"),
    pushChanges
  )
)

```

See: 
```
Please enter PGP passphrase (or ENTER to abort): *********
[error] java.io.IOException: destination file exists and overwrite == false
[error]         at org.apache.ivy.plugins.repository.url.URLRepository.put(URLRepository.java:75)
[error]         at sbt.internal.librarymanagement.ConvertResolver$LocalIfFileRepo.put(ConvertResolver.scala:365)
[error]         at org.apache.ivy.plugins.repository.AbstractRepository.put(AbstractRepository.java:130)
[error]         at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put(ConvertResolver.scala:117)
[error]         at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put$(ConvertResolver.scala:104)
[error]         at sbt.internal.librarymanagement.ConvertResolver$$anonfun$defaultConvert$lzycompute$1$PluginCapableResolver$1.put(ConvertResolver.scala:164)
[error]         at org.apache.ivy.plugins.resolver.RepositoryResolver.publish(RepositoryResolver.java:216)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5(IvyActions.scala:499)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5$adapted(IvyActions.scala:498)
[error]         at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:944)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:944)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]         at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
[error]         at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:498)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$3(IvyActions.scala:144)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.internal.librarymanagement.IvyActions$.withChecksums(IvyActions.scala:157)
[error]         at sbt.internal.librarymanagement.IvyActions$.withChecksums(IvyActions.scala:151)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$1(IvyActions.scala:144)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$1$adapted(IvyActions.scala:134)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error]         at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error]         at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]         at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error]         at xsbt.boot.Using$.withResource(Using.scala:10)
[error]         at xsbt.boot.Using$.apply(Using.scala:9)
[error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]         at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
[error]         at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:134)
[error]         at sbt.Classpaths$.$anonfun$publishTask$4(Defaults.scala:2244)
[error]         at sbt.Classpaths$.$anonfun$publishTask$4$adapted(Defaults.scala:2243)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:272)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] java.io.IOException: destination file exists and overwrite == false
[error]         at org.apache.ivy.plugins.repository.url.URLRepository.put(URLRepository.java:75)
[error]         at sbt.internal.librarymanagement.ConvertResolver$LocalIfFileRepo.put(ConvertResolver.scala:365)
[error]         at org.apache.ivy.plugins.repository.AbstractRepository.put(AbstractRepository.java:130)
[error]         at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put(ConvertResolver.scala:117)
[error]         at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put$(ConvertResolver.scala:104)
[error]         at sbt.internal.librarymanagement.ConvertResolver$$anonfun$defaultConvert$lzycompute$1$PluginCapableResolver$1.put(ConvertResolver.scala:164)
[error]         at org.apache.ivy.plugins.resolver.RepositoryResolver.publish(RepositoryResolver.java:216)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5(IvyActions.scala:499)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5$adapted(IvyActions.scala:498)
[error]         at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:944)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:944)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]         at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
[error]         at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:498)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$3(IvyActions.scala:144)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.internal.librarymanagement.IvyActions$.withChecksums(IvyActions.scala:157)
[error]         at sbt.internal.librarymanagement.IvyActions$.withChecksums(IvyActions.scala:151)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$1(IvyActions.scala:144)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$1$adapted(IvyActions.scala:134)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error]         at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error]         at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]         at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error]         at xsbt.boot.Using$.withResource(Using.scala:10)
[error]         at xsbt.boot.Using$.apply(Using.scala:9)
[error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]         at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
[error]         at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:134)
[error]         at sbt.Classpaths$.$anonfun$publishTask$4(Defaults.scala:2244)
[error]         at sbt.Classpaths$.$anonfun$publishTask$4$adapted(Defaults.scala:2243)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:272)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (core / publishSigned) java.io.IOException: destination file exists and overwrite == false
[error] (akka / publishSigned) java.io.IOException: destination file exists and overwrite == false

```

**Comment by eed3si9n** [comment]
@pathikrit Are you using the latest sbt and sbt-pgp?

**Comment by nhooey** [comment]
@eed3si9n, @dwijnand, @wsargent: This still happens with `sbt 1.1.5` when publishing to Artifactory. The source and destination file aren't printed.

**Exception message:**
```
[error] (publish) java.io.IOException: destination file exists and overwrite == false
```

**Full log:**
```
$ sbt publish
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /builds/Organization/scala/name-of-package/.sbt/staging/4faa8edd4c4c9f9b8e54/build-plugin/project
[info] Loading settings from build.sbt ...
[info] Loading project definition from /builds/Organization/scala/name-of-package/project
[info] Loading settings from build.sbt ...
[info] Setting Java TimeZone default to UTC
git version 2.15.0
v0.0.8
[info] Set current project to name-of-package (in build file:/builds/Organization/scala/name-of-package/)
[info] Packaging /builds/Organization/scala/name-of-package/target/scala-2.12/name-of-package_2.12-v0.0.8-sources.jar ...
[info] Done packaging.
[info] Wrote /builds/Organization/scala/name-of-package/target/scala-2.12/name-of-package_2.12-v0.0.8.pom
[info] Main Scala API documentation to /builds/Organization/scala/name-of-package/target/scala-2.12/api...
[info] Packaging /builds/Organization/scala/name-of-package/target/scala-2.12/name-of-package_2.12-v0.0.8.jar ...
[info] Done packaging.
[warn] there were two feature warnings; re-run with -feature for details
model contains 30 documentable templates
[warn] one warning found
[info] Main Scala API documentation successful.
[info] Packaging /builds/Organization/scala/name-of-package/target/scala-2.12/name-of-package_2.12-v0.0.8-javadoc.jar ...
[info] Done packaging.
[error] java.io.IOException: destination file exists and overwrite == false
[error] 	at org.apache.ivy.plugins.repository.url.URLRepository.put(URLRepository.java:75)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$LocalIfFileRepo.put(ConvertResolver.scala:365)
[error] 	at org.apache.ivy.plugins.repository.AbstractRepository.put(AbstractRepository.java:130)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put(ConvertResolver.scala:117)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put$(ConvertResolver.scala:104)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$$anonfun$defaultConvert$lzycompute$1$PluginCapableResolver$1.put(ConvertResolver.scala:164)
[error] 	at org.apache.ivy.plugins.resolver.RepositoryResolver.publish(RepositoryResolver.java:216)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5(IvyActions.scala:499)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5$adapted(IvyActions.scala:498)
[error] 	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:944)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:944)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error] 	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
[error] 	at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:498)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$3(IvyActions.scala:144)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.internal.librarymanagement.IvyActions$.withChecksums(IvyActions.scala:157)
[error] 	at sbt.internal.librarymanagement.IvyActions$.withChecksums(IvyActions.scala:151)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$1(IvyActions.scala:144)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$1$adapted(IvyActions.scala:134)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
[error] 	at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:134)
[error] 	at sbt.Classpaths$.$anonfun$publishTask$4(Defaults.scala:2244)
[error] 	at sbt.Classpaths$.$anonfun$publishTask$4$adapted(Defaults.scala:2243)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:272)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (publish) java.io.IOException: destination file exists and overwrite == false
[error] Total time: 13 s, completed May 24, 2018 6:27:05 PM
```

**Comment by nhooey** [comment]
@eed3si9n: Please re-open this issue because it's still happening with `sbt 1.1.5`.

**Comment by eaplatanios** [comment]
@nhooey What version of sbt-pgp are you using? As far as I know, this issue has to do with sbt-pgp rather than SBT and was fixed a while ago. Does it still occur if you use the latest version of sbt-pgp?

**Comment by dwijnand** [comment]
Rather than necro this issue, let's open a new issue (or, if there are distinct problems, multiple) to either sbt/sbt or sbt/sbt-pgp, which makes sure that (1) the issue template is (hopefully!) followed when reporting a problem, and (2) avoids mutating the milestone an issue was resolved in (or at least attempted to be resolved in).
