### ISSUE TITLE
There should be a way to disable java version checking built into sbt.

### ISSUE THREAD

**Issue by markehammons** [sbt/sbt#4004]
(See the guidelines for contributing, linked above)

## steps
Set java 10 early access build as your provider of the java executable
Try to launch sbt

## problem
sbt throws an error saying the java version is too old. It fails to parse the version string of java 10 because the current builds include a date in the versioning.

## expectation
there should be a way to force sbt to try to run with the java provided, for testing purposess

sbt version: 1.1.0

**Comment by itohiro73** [comment]
(cc: @eed3si9n)
I tried to reproduce this but I couldn't in my Mac OS (High Sierra 10.13.3) . Here is the Java version I tried.

```
# java --version 
java 10 2018-03-20
Java(TM) SE Runtime Environment 18.3 (build 10+46)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10+46, mixed mode)
# sbt 
[info] Loading settings from idea.sbt ...
[info] Loading global plugins from /Users/hiroshi/.sbt/1.0/plugins
Waiting for lock on /Users/hiroshi/.ivy2/.sbt.ivy.lock to be available...

[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /Users/hiroshi/Development/github/itohiro73/sbt/project
[info] Loading settings from build.sbt ...
[info] Resolving key references (12377 settings) ...
[info] Set current project to sbtRoot (in build file:/Users/hiroshi/Development/github/itohiro73/sbt/)
[info] sbt server started at local:///Users/hiroshi/.sbt/1.0/server/0e164567190001c42432/sock
sbt:sbtRoot> 
```

@markehammons Would you mind providing your OS, the exact Java version, sbt launcher version and the step that you encountered this issue?

**Comment by markehammons** [comment]
I was using opensuse tumbleweed linux. Unfortunately I switched back to fedora, but I can retry with the java 10 eap.

**Comment by rcano** [comment]
Ubuntu 17.10 here, fresh install of java 10 from oracle's download site, sbt errs with:

```
expr: syntax error

The Java Development Kit (JDK) installation you have is not up to date.
requires at least version 1.6+, you have
version 10 2018-03-20

Please go to http://www.oracle.com/technetwork/java/javase/downloads/ and download
a valid JDK and install before running .
```

**Comment by dwijnand** [comment]
fixed in https://github.com/sbt/sbt-launcher-package/pull/209 (sbt 1.1.1)

**Comment by markehammons** [comment]
@dwijnand I'm still encountering the error:

```
[process_args] java_version = '10'

The Java Development Kit (JDK) installation you have is not up to date.
requires at least version 1.6+, you have
version 10

Please go to http://www.oracle.com/technetwork/java/javase/downloads/ and download
a valid JDK and install before running .
```

I still think an override for this version testing would be a good idea, especially for testing on non-openjdk based jdks.

For extra information, I've installed sbt via the rpm repository provided by [this page](https://www.scala-sbt.org/download.html), and I've made certain I'm up to date.

**Comment by dwijnand** [comment]
https://github.com/sbt/sbt-launcher-package/pull/209#issuecomment-375861115
