### ISSUE TITLE
Referencing classes in java.sql in Java 9 or later from sbt console throws SecurityException

### ISSUE THREAD

**Issue by willbeason** [sbt/sbt#4328]
- [X] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## steps

Basically, doing anything in the console that directly creates an object in java.sql while using Java 9 or later will produce this bug.

1. Switch to Java 9 or later
2. Put `libraryDependencies += "org.postgresql" % "postgresql" % "42.2.4"` in `build.sbt`
3. `sbt console`
4. Run the code below:

```
import java.sql.DriverManager
import java.util.Properties

val credentials = new Properties()
credentials.setProperty("user", "my_user")
credentials.setProperty("password", "my_password")

val url = "jdbc:postgresql://localhost:5432/postgres"

DriverManager.getConnection(url, credentials)
```

## problem

SBT Console throws a SecurityException.

```
scala> DriverManager.getConnection(url, properties)
java.lang.SecurityException: Prohibited package name: java.sql
  at java.base/java.lang.ClassLoader.preDefineClass(ClassLoader.java:891)
  at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1007)
  at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
  at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:545)
  at java.base/java.net.URLClassLoader.access$100(URLClassLoader.java:83)
  at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:453)
  at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:447)
  at java.base/java.security.AccessController.doPrivileged(Native Method)
  at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:446)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:553)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
  at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
  at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3119)
  at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3144)
  at java.base/java.lang.Class.getMethods(Class.java:1863)
  at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.evalMethod(IMain.scala:855)
  at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:788)
  at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1054)
  at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:645)
  at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:644)
  at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
  at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
  at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:644)
  at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:576)
  at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
  at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:819)
  at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:691)
  at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:404)
  at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:425)
  at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:993)
  at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:891)
  at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:891)
  at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:97)
  at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:891)
  at xsbt.ConsoleInterface.run(ConsoleInterface.scala:71)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:564)
  at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
  at sbt.internal.inc.AnalyzingCompiler.console(AnalyzingCompiler.scala:199)
  at sbt.Console.console0$1(Console.scala:48)
  at sbt.Console.$anonfun$apply$2(Console.scala:51)
  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
  at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
  at sbt.TrapExit$App.run(TrapExit.scala:253)
  at java.base/java.lang.Thread.run(Thread.java:844)
```

## expectation

SBT Console creates a connection to Postgres without throwing an exception.

## notes

Downgrading Java to 8 immediately fixes the issue. In some cases, putting the logic that handles `java.sql` inside a class in another file resolves the issue (but other times it doesn't - I'm not sure of the pattern).

[Stack Overflow Question](https://stackoverflow.com/questions/51790356/how-to-reference-java-sql-from-a-scala-script-without-encountering-securityexcep)

Java Version: 10.0.1
Scala Version: 2.12.4
sbt Version: 1.2.0

**Comment by eed3si9n** [comment]
@willbeason Thanks for the report with repro project.

**Comment by eed3si9n** [comment]
Given that `run` seems to work (I get `java.net.ConnectException: Connection refused`), I wonder if this is something specific to the way `console` is constructing the classloader.

**Comment by willbeason** [comment]
You're right, it does work with `run`. However, I found that in some cases (but, curiously, not all), if an external library inherits from a class in java.sql then you get the same error:

`mypackage/Main.scala`
```
import com.sun.rowset.FilteredRowSetImpl
object Main {

  def main(args: Array[String]): Unit = {
    val rowSet = new FilteredRowSetImpl()
  }

}
```

Running the main class:
```
mypackage$ sbt run
[info] Loading settings for project global-plugins from idea.sbt ...
[info] Loading global plugins from /home/willbeason/.sbt/1.0/plugins
[info] Loading project definition from /home/willbeason/IdeaProjects/mypackage/project
[info] Loading settings for project mypackage from build.sbt ...
[info] Set current project to mypackage (in build file:/home/willbeason/IdeaProjects/mypackage/)
[info] Compiling 1 Scala source to /home/willbeason/IdeaProjects/mypackage/target/scala-2.12/classes ...
[info] Done compiling.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/home/willbeason/.sbt/boot/scala-2.12.6/org.scala-sbt/sbt/1.2.0/protobuf-java-3.3.1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[info] Packaging /home/willbeason/IdeaProjects/mypackage/target/scala-2.12/mypackage_2.12-0.1.jar ...
[info] Done packaging.
[info] Running mypackage.Main 
[error] (run-main-0) javax.sql.rowset.spi.SyncFactoryException: IllegalAccessException: com.sun.rowset.providers.RIOptimisticProvider
[error] javax.sql.rowset.spi.SyncFactoryException: IllegalAccessException: com.sun.rowset.providers.RIOptimisticProvider
[error] 	at java.sql.rowset/javax.sql.rowset.spi.SyncFactory.getInstance(SyncFactory.java:590)
[error] 	at java.sql.rowset/com.sun.rowset.CachedRowSetImpl$1.run(CachedRowSetImpl.java:367)
[error] 	at java.sql.rowset/com.sun.rowset.CachedRowSetImpl$1.run(CachedRowSetImpl.java:364)
[error] 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[error] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:724)
[error] 	at java.sql.rowset/com.sun.rowset.CachedRowSetImpl.<init>(CachedRowSetImpl.java:364)
[error] 	at java.sql.rowset/com.sun.rowset.WebRowSetImpl.<init>(WebRowSetImpl.java:86)
[error] 	at java.sql.rowset/com.sun.rowset.FilteredRowSetImpl.<init>(FilteredRowSetImpl.java:59)
[error] 	at mypackage.Main$.main(Main.scala:8)
[error] 	at mypackage.Main.main(Main.scala)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[error] Nonzero exit code: 1
[error] (Compile / run) Nonzero exit code: 1
[error] Total time: 3 s, completed Aug 21, 2018, 9:47:23 AM
```

**Comment by larroy** [comment]
This also causes problems when using spark in the sbt console:

```
import org.apache.spark.sql.SparkSession
import org.apache.spark.sql.functions._
val spark = SparkSession.builder().master("local").appName("spark-shell").getOrCreate()
import spark.implicits._
val sc = spark.sparkContext
val sourceDF = Seq(
  ("jets", "football"),
  ("nacional", "soccer")
).toDF("team", "sport")
```
Version 1.2.8

```


```

**Comment by schlichtanders** [comment]
I also run into this just now, I wanted to work with a SparkSession within sbt console.
Seems that I have to go back to java 8 as a workaround...

it would be very helpful, if this issue could be addressed

**Comment by techmag** [comment]
Is there at least a work-around for this yet (other than backing down to Java 8)?

**Comment by TK009** [comment]
I just wanted to use `java.sql.Timestamp` and I get a similar SecurityException.
So here is a simpler test case:
```scala
new java.sql.Timestamp(1)
```

Result:

```
[info] welcome to sbt 1.5.5 (Oracle Corporation Java 11.0.12)
...
Welcome to Scala 2.12.14 (OpenJDK 64-Bit Server VM, Java 11.0.12).
...
scala> new java.sql.Timestamp(1)
java.lang.SecurityException: Prohibited package name: java.sql
  at java.base/java.lang.ClassLoader.preDefineClass(ClassLoader.java:899)
  ...
```
sbt version 1.5.5

**Comment by eed3si9n** [comment]
Googling around I came across a similar issue in Mill that's been fixed https://github.com/lihaoyi/mill/issues/251

We could try applying a similar fix.

**Comment by eed3si9n** [comment]
So looks like the idea is to inject rt.jar into classpath and also making sure platform classloader gets used as parent on JVM 9+. I need to think a bit more if this is a fix we would want for sbt in the long term.

If we keep emulating things like run and console as function call maybe these hacks are necessary, but I feel like `--add-modules` should be supported only for forking. But forking doesn't exist for console.

**Comment by armtuk** [comment]
Just ran into this tonight trying to test some date conversion shenanigans on the REPL.

**Comment by luisguzman02** [comment]
Is there a workaround for this exception? tried passing --add-modules but still getting the same exception

**Comment by armtuk** [comment]
And here I find myself again - trying to debug a MSSQLServer connection unable to do it from the console. Gah.

**Comment by yamin-oanda** [comment]
I wonder if Ammonite REPL can handle this?

**Comment by tmccombs** [comment]
I am very suspicious that this is related to https://github.com/sbt/sbt-jmh/issues/192. I'm guessing that the `java.sql` package isn't available during the compilation step for Jmh either.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/zinc/pull/1706

**Comment by BrianHotopp** [comment]
Still reproduces on sbt 1.11.7 / JDK 21. The merged zinc fix covers the 2.x path
only; the 1.x failure happens below ClasspathFilter, when the REPL's
URLClassLoader defines `java.*` bytes found in the generated java9-rt-ext jar.
Fix: #9327.
