### ISSUE TITLE
Adding a call to super in a trait should trigger recompilation of implementing classes

### ISSUE THREAD

**Issue by Blaisorblade** [sbt/sbt#466]
Incremental recompilation fails to consider the translation of calls to 'super.method' in a trait; the resulting code causes an `AbstractMethodError` at runtime. Below an example and analysis of the effects.

Note that if I misdiagnosed the problem, the below reduced data might be incorrect - ellipsis indicate text which I removed because I considered it irrelevant.

Consider the following change:

``` scala
 trait QueryBenchmarking {
-  override def debugBench = onlyOptimized
+  override def debugBench = super.debugBench || onlyOptimized
   def onlyOptimized: Boolean = ...
   ...
 }
```

`javap QueryBenchmarking` shows that after this change, the interface corresponding to this trait has a new abstract method called `performancetests$QueryBenchmarking$$super$debugBench()`:

``` java
public interface performancetests.QueryBenchmarking extends ...,scala.ScalaObject{
    public abstract boolean performancetests$QueryBenchmarking$$super$debugBench();
    public abstract boolean onlyOptimized();
    public abstract boolean debugBench();
    ...
}
```

Let's assume that class `Foo` implements this trait; now `Foo` needs to be recompiled just to implement `performancetests$QueryBenchmarking$$super$debugBench()` correctly (by delegating calls to the right implementation chosen by linearization); `QueryBenchmarking` did not have this abstract method before. I noticed because I got an `AbstractMethodError` when running the code _inside_ SBT; I have not checked that SBT did not recompile `Foo`, but running `compile` again did not fix the problem, which was instead fixed by manually forcing recompilation of `Foo` (by modifying it).

This error is quite confusing, because I would expect that if I add an abstract method to a class/trait, SBT should recompile also unmodified descendant classes (and probably discover that now they must be altered). I would speculate that such `$$super$` method are added by Scalac _after_ the API of the output is computed, which seems however quite annoying, but I haven't read the sources.

**Comment by Blaisorblade** [comment]
Should I report this bug on the Scalac issue tracker as a build manager bug? I need somebody with a bigger clue than me to confirm that this is the correct action - also because Googling `scala build manager` suggests it to be a user-visible feature of ScalaIDE (http://www.assembla.com/spaces/scala-ide/wiki/SBT-based_build_manager) and not the internal compiler component actually causing the error.

**Comment by harrah** [comment]
Yes, this one is hard to handle as it isn't covered by the source API (other implementation details usually are).  Also, a scripted test demonstrating the problem would be appreciated.

The refined build manager is, to my knowledge, not actively maintained, but you could file the bug anyway.  The scala.tools.nsc.interactive.BuildManagerTest can be used to test the refined build manager manually and I think there is a way to write build manager tests for partest.

**Comment by Blaisorblade** [comment]
I had misunderstood what the build manager was, I thought it was what you called the "source API".
Since SBT gets the resulting interface through the compiler, this problem could be due to a compiler bug. Or maybe SBT should just query information not after type but after the next phase, [superaccessors](http://lampwww.epfl.ch/~magarcia/ScalaCompilerCornerReloaded/); this looks conceptually clear, but I have no idea if it's feasible.

For the scripted test, I'll try to get there at some point - for now I'm progressing towards Scalac SI-3452 and with reducing another SBT bug.

**Comment by OlegYch** [comment]
was this fixed?
i'm experincing something similar
i.e. when i add a private val to a trait which is mixed in some class i get AME from constructor of that class

**Comment by Blaisorblade** [comment]
I think this isn't fixed — I've run into it today as of 0.13.1 (even though by now the API is extracted after pickler, which runs after superaccessors, so there must be some other issue at hand).
But what you describe sounds different (to me), because this issue was up to now specifically about super accessors. Can you post a reduced example?
(Maybe the issue is in fact about the addition of synthetic methods...)

**Comment by OlegYch** [comment]
i'm not able to minimize it
here is the essence of my code https://github.com/OlegYch/sbt-test/tree/466
when you do testIncrementalCompile in that project it will add a private field to a trait
as a result sbt recompiles only the modified file
this causes AME in my real project, but not in the minimized one
not sure why...

**Comment by OlegYch** [comment]
uh well, i misinterpreted the output, it does recompile both files in minimized project so no AME in it, but somehow it doesn't in my project

**Comment by OlegYch** [comment]
and it's 100% reproducible, even after clean and subsequent incremental recompilation

**Comment by Blaisorblade** [comment]
That's cool, you certainly now more about SBT than me. But the project you linked is the one after minimization, and I guess the non-minimized source is not public, is it?

How did you proceed in minimizing?
I suspect you just recreated what you guessed was required to reproduce the bug, which is often sensible, but not here. From my experience with Scalac (which is relevant here), triggering the bug might depend on a lot of stuff which shouldn't matter — keeping the classes nested, and even in the extreme case having enough other files around (if you want to see the nightmare debugging, look at the "minimization" described here: https://groups.google.com/d/msg/scala-internals/ZtEdwDwEn4U/BvVhKWRI6BAJ).

My approach would be here to start minimizing from the existing project, cutting away pieces as long as it keeps failing, in binary-search fashion — you might end up with something bigger, but at least it'll keep failing. If the source is proprietary, you can still (probably) at least remove most method bodies (replacing them with ???) and rename classes to meaningless names (if you can't remove classes without hiding the bug).

> uh well, i misinterpreted the output, it does recompile both files in minimized project so no AME in it, but somehow it doesn't in my project

That's because the files are recompiled one at a time, right? Below's the output I get, and it seems it might be recompiling both files (the changed one and then the client code); I managed to read the output from last and confirm that's what's happening. The output of `last` mentions "transitive public inheritance", but that "public" puzzles me — does the bug trigger with some form of "private inheritance"? I didn't know it exists.

```
[debug] Invalidated by transitive public inheritance: Set(/Users/pgiarrusso/Documents/Research/Sorgenti/sbt-test/src/main/scala/B.scala)
```

```
[info] running incremental compilation
[info] Compiling 1 Scala source to /Users/pgiarrusso/Documents/Research/Sorgenti/sbt-test/target/scala-2.10/classes...
[warn] there were 2 feature warning(s); re-run with -feature for details
[warn] one warning found
[info] Compiling 1 Scala source to /Users/pgiarrusso/Documents/Research/Sorgenti/sbt-test/target/scala-2.10/classes...
[info] Analysis: 2 Scala sources, 10 classes, 2 binary dependencies, 2 unreported warnings
```

**Comment by gkossakowski** [comment]
Guys, could you give name hashing a try? Amongst other things, it has improved logging of incremental compiler activity.

Also, if you want to understand why recompilation is/isn't triggered I recommend checking api-diff, see: http://www.scala-sbt.org/release/docs/Detailed-Topics/Understanding-incremental-recompilation.html#debugging-an-interface-representation

**Comment by OlegYch** [comment]
@gkossakowski 'last compile' is empty for some reason

**Comment by gkossakowski** [comment]
Which version are you testing? There was an issue with "last" command: https://groups.google.com/d/msg/sbt-dev/KmGEhFTMve0/HWCJmoK_OCAJ

It was fixed in nightly build of sbt. Instead of using `last` command you can just set different debugging level for compile command:

```
set logLevel in compile := Level.Debug
```

All debugging logs will be printed to the console.

**Comment by OlegYch** [comment]
here is the log https://gist.github.com/OlegYch/082b44af83449fb076a8
i'm using M2 atm because M3 breaks native-packager, but the issue persists in M3, and 0.13.1

**Comment by OlegYch** [comment]
curiously, when i perform compile after changed sources where  just compiled the log output is the same

**Comment by Blaisorblade** [comment]
The debugging output looks broken in multiple ways, but the debugging feature seems to work well on the minimized (and non-bug-inducing) project.

The log seems indeed the same, including the `with java.lang.this#Objectwith scala.this#Any` part.
Is it my impression or the "old" side of the diff is rather corrupted?

Also, why does the new code seem to contain "recursive inheritance" (types inheriting from themselves)? `class com.server.cache.Cache requires com.server.cache.this#Cache`?

For reference, the changes I used on the minimized project are here: https://github.com/Blaisorblade/sbt-test/compare/466. Not that I expect much error-proneness for those changes.

**Comment by bitloi** [comment]
@eed3si9n Can you let me know if this issue is still necessary?

**Comment by eed3si9n** [comment]
Yes. trait-super scripted test exists in Zinc, and it was fixed a while back - https://github.com/sbt/zinc/tree/develop/zinc/src/sbt-test/source-dependencies/trait-super
