### ISSUE TITLE
Stay on Scala 2.12.8?

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt#4935]
Given https://github.com/scala/bug/issues/11665 (String interpolation containing 33 non-String would fail), I wonder if we should stick to Scala 2.12.8 until 2.12.10 comes out and fixes it.

**Comment by eatkins** [comment]
That seems fine. I wanted to bump because sbt works best overall when the sbt version matches the project version. I have noticed some weirdness with sbt sometimes seeming to hang for a while when using a locally published 2.12.9 version. I can’t actually blame 2.12.9 directly but I’ve had a nagging suspicion that there may have been some regressions in 2.12.9.

**Comment by markehammons** [comment]
I'm currently testing an early access version of java 14 with sbt 1.3.0-RC3, and it seems scala 2.12.8 is really incompatible with it.

```
[error] java.io.IOError: java.lang.RuntimeException: /packages cannot be represented as URI
[error]         at java.base/jdk.internal.jrtfs.JrtPath.toUri(JrtPath.java:176)
[error]         at scala.tools.nsc.classpath.JrtClassPath.asURLs(DirectoryClassPath.scala:204)
```

[Here's the code in scala 2.18 triggering the exception](https://github.com/scala/scala/blob/38cd84d976880eab16af17a44d186bbddcd554f2/src/compiler/scala/tools/nsc/classpath/DirectoryClassPath.scala#L213)

I don't know if scala 2.12.9+ remedies the situation, but the code it's using is different, and hopefully wouldn't die.

**Comment by plokhotnyuk** [comment]
@eatkins Possible you have hit [this](https://github.com/scala/bug/issues/11667) issue of compile time regression.

Also, there are unreported issues with 2.12.9 like [here](https://github.com/7mind/izumi/commit/c9d31508ba364c0c0830b6c652e31bfe699c860f)

**Comment by eed3si9n** [comment]
@markehammons That was fixed in 2.12.9 (https://github.com/scala/scala/releases/tag/v2.12.9) - https://github.com/scala/scala/pull/8210

**Comment by SethTisue** [comment]
> Also, there are unreported issues with 2.12.9 like here

at the link you provided, I requested a bug report

but I notice that you say unreported "issues", plural? what else are you aware of?

**Comment by plokhotnyuk** [comment]
@SethTisue 

- org.scalameta#semanticdb-scalac_2.12.9;4.1.9: not found: https://api.travis-ci.org/v3/job/568969163/log.txt
- unexpected 10% slowdown of the build (comparing with 2.12.6): https://github.com/broadinstitute/cromwell/pull/5106

**Comment by SethTisue** [comment]
> * org.scalameta#semanticdb-scalac_2.12.9;4.1.9: not found: https://api.travis-ci.org/v3/job/568969163/log.txt

it appears that the scalameta folks simply haven't published for 2.12.9 yet; there is already a ticket on that at https://github.com/scalameta/scalameta/issues/1892

> unexpected 10% slowdown of the build (comparing with 2.12.6): broadinstitute/cromwell#5106

it sounds to me like they got a speedup, not a slowdown

**Comment by plokhotnyuk** [comment]
@SethTisue ups, sorry I misread the PR comment... but I'm happy that there are no unreported issues for 2.12.9

**Comment by SethTisue** [comment]
thanks for keeping an eye out!

**Comment by dwijnand** [comment]
"Fixed" in #4936?

**Comment by eed3si9n** [comment]
@dwijnand Yea.

**Comment by yonghaoy** [comment]
I am still having the issue with Scala 2.13.1, JDK 13 and sbt 1.3.8:

: java.lang.RuntimeException: /packages cannot be represented as URI
[error] at java.base/jdk.internal.jrtfs.JrtPath.toUri(JrtPath.java:176)
[error] at scala.tools.nsc.classpath.JrtClassPath.asURLs(DirectoryClassPath.scala:204)
[error] at scala.tools.nsc.classpath.AggregateClassPath.$anonfun$asURLs$1(AggregateClassPath.scala:55)
[error] at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:240)
[error] at scala.collection.Iterator.foreach(Iterator.scala:937)
[error] at scala.collection.Iterator.foreach$(Iterator.scala:937)
[error] at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
[error] at scala.collection.IterableLike.foreach(IterableLike.scala:70)
[error] at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
[error] at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error] at scala.collection.TraversableLike.flatMap(TraversableLike.scala:240)
[error] at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:237)
[error] at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[error] at scala.tools.nsc.classpath.AggregateClassPath.asURLs(AggregateClassPath.scala:55)
[error] at scala.tools.nsc.typechecker.Macros.findMacroClassLoader(Macros.scala:66)
[error] at scala.tools.nsc.typechecker.Macros.findMacroClassLoader$(Macros.scala:65)
[error] at scala.tools.nsc.Global$$anon$1.findMacroClassLoader(Global.scala:469)
[error] at scala.reflect.macros.runtime.MacroRuntimes.$anonfun$defaultMacroClassloaderCache$2(MacroRuntimes.scala:56)
[error] at scala.reflect.internal.SymbolTable$perRunCaches$$anon$1.apply(SymbolTable.scala:457)
[error] at scala.reflect.macros.runtime.MacroRuntimes.defaultMacroClassloader(MacroRuntimes.scala:58)
[error] at scala.reflect.macros.runtime.MacroRuntimes.defaultMacroClassloader$(MacroRuntimes.scala:58)
[error] at scala.tools.nsc.Global$$anon$1.defaultMacroClassloader(Global.scala:469)
[error] at scala.reflect.macros.runtime.MacroRuntimes$MacroRuntimeResolver.resolveRuntime(MacroRuntimes.scala:76)
[error] at scala.reflect.macros.runtime.MacroRuntimes.$anonfun$standardMacroRuntime$3(MacroRuntimes.scala:38)
[error] at scala.collection.mutable.MapLike.getOrElseUpdate(MapLike.scala:206)
[error] at scala.collection.mutable.MapLike.getOrElseUpdate$(MapLike.scala:203)
[error] at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
[error] at scala.reflect.macros.runtime.MacroRuntimes.standardMacroRuntime(MacroRuntimes.scala:38)
[error] at scala.reflect.macros.runtime.MacroRuntimes.standardMacroRuntime$(MacroRuntimes.scala:31)
[error] at scala.tools.nsc.Global$$anon$1.standardMacroRuntime(Global.scala:469)
[error] at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$14.default(AnalyzerPlugins.scala:448)
[error] at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$14.default(AnalyzerPlugins.scala:445)
[error] at scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:401)
[error] at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroRuntime(AnalyzerPlugins.scala:445)
[error] at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroRuntime$(AnalyzerPlugins.scala:445)
[error] at scala.tools.nsc.Global$$anon$1.pluginsMacroRuntime(Global.scala:469)
[error] at scala.reflect.macros.runtime.MacroRuntimes.macroRuntime(MacroRuntimes.scala:25)
[error] at scala.reflect.macros.runtime.MacroRuntimes.macroRuntime$(MacroRuntimes.scala:25)
[error] at scala.tools.nsc.Global$$anon$1.macroRuntime(Global.scala:469)
[error] at scala.tools.nsc.typechecker.Macros$MacroExpander.$anonfun$expand$1(Macros.scala:619)
[error] at scala.tools.nsc.Global.withInfoLevel(Global.scala:219)
[error] at scala.tools.nsc.typechecker.Macros$MacroExpander.expand(Macros.scala:613)
[error] at scala.tools.nsc.typechecker.Macros$MacroExpander.apply(Macros.scala:600)
[error] at scala.tools.nsc.typechecker.Macros.standardMacroExpand(Macros.scala:764)
[error] at scala.tools.nsc.typechecker.Macros.standardMacroExpand$(Macros.scala:762)
[error] at scala.tools.nsc.Global$$anon$1.standardMacroExpand(Global.scala:469)
[error] at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$12.default(AnalyzerPlugins.scala:432)
[error] at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$12.default(AnalyzerPlugins.scala:429)
[error] at scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:401)
[error] at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand(AnalyzerPlugins.scala:429)
[error] at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand$(AnalyzerPlugins.scala:429)
[error] at scala.tools.nsc.Global$$anon$1.pluginsMacroExpand(Global.scala:469)
[error] at scala.tools.nsc.typechecker.Macros.macroExpand(Macros.scala:757)
[error] at scala.tools.nsc.typechecker.Macros.macroExpand$(Macros.scala:757)
[error] at scala.tools.nsc.Global$$anon$1.macroExpand(Global.scala:469)
[error] at scala.tools.nsc.typechecker.Typers$Typer.vanillaAdapt$1(Typers.scala:1163)
[error] at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1223)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5631)
[error] at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$adapt$1(Typers.scala:881)
[error] at scala.tools.nsc.typechecker.Typers$Typer.adaptToImplicitMethod$1(Typers.scala:471)
[error] at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1219)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5631)
[error] at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedArg$1(Typers.scala:3280)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:471)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typedArgToPoly$1(Typers.scala:3670)
[error] at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$doTypedApply$33(Typers.scala:3678)
[error] at scala.tools.nsc.typechecker.Typers$Typer.handlePolymorphicCall$1(Typers.scala:3678)
[error] at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3689)
[error] at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4767)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4776)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5571)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5617)
[error] at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedArg$1(Typers.scala:3280)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:471)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typedArgToPoly$1(Typers.scala:3670)
[error] at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$doTypedApply$33(Typers.scala:3678)
[error] at scala.tools.nsc.typechecker.Typers$Typer.handlePolymorphicCall$1(Typers.scala:3678)
[error] at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3689)
[error] at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4767)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4776)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5571)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5617)
[error] at scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:5692)
[error] at scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:1079)
[error] at scala.tools.nsc.typechecker.Namers$Namer.valDefSig(Namers.scala:1629)
[error] at scala.tools.nsc.typechecker.Namers$Namer.memberSig(Namers.scala:1798)
[error] at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1763)
[error] at scala.tools.nsc.typechecker.Namers$Namer$ValTypeCompleter.completeImpl(Namers.scala:910)
[error] at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:1960)
[error] at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:1958)
[error] at scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:1953)
[error] at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1530)
[error] at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1678)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5240)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5617)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5681)
[error] at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3264)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3264)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1999)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1868)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5538)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5617)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5681)
[error] at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3264)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3264)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5247)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5540)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5617)
[error] at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:106)
[error] at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:441)
[error] at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.run(Analyzer.scala:96)
[error] at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1467)
[error] at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1451)
[error] at scala.tools.nsc.Global$Run.compileSources(Global.scala:1444)
[error] at scala.tools.nsc.Global$Run.compile(Global.scala:1567)
[error] at xsbt.CachedCompiler0.run(CompilerInterface.scala:130)
[error] at xsbt.CachedCompiler0.run(CompilerInterface.scala:105)
[error] at xsbt.CompilerInterface.run(CompilerInterface.scala:31)
[error] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[error] at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
[error] at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
[error] at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
[error] at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error] at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:133)
[error] at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:73)
[error] at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:116)
[error] at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:307)
[error] at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:307)
[error] at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:106)
[error] at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:87)
[error] at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:116)
[error] at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:63)
[error] at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:89)
[error] at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:134)
[error] at sbt.internal.inc.Incremental$.compile(Incremental.scala:80)
[error] at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:67)
[error] at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:311)
[error] at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:269)
[error] at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:159)
[error] at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:238)
[error] at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:69)
[error] at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1544)
[error] at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1518)
[error] at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] at sbt.Execute.work(Execute.scala:278)
[error] at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] at java.base/java.lang.Thread.run(Thread.java:830)

**Comment by SethTisue** [comment]
@yonghaoy I see you also reported that at https://github.com/sbt/sbt/issues/5093 . let's discuss there, not here
