### ISSUE TITLE
"/packages cannot be represented as URI" on JDK 13

### ISSUE THREAD

**Issue by mr-git** [sbt/sbt#5093]
## steps
SBT 1.3.0
OpenJDK 13
macOS 10.14.6

## problem
build.sbt:
```
lazy val root = project.in(file("."))
```
start SBT session:
* if started on OpenJDK 12 (11, 10, 9), SBT starts
* when started on OpenJDK 13 - SBT startup fails with:
```
[error] java.io.IOError: java.lang.RuntimeException: /packages cannot be represented as URI
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

## expectation
SBT work on OpenJDK 13

## notes
if `build.sbt` is defined like:
```
lazy val root = project
```
SBT 1.3.0 manages to start on OpenJDK 13

Similar issue was made earlier this year for Scala: https://github.com/scala/bug/issues/11608

**Comment by eed3si9n** [comment]
@mr-git Thanks for the report.

This was a known issue with Scala 2.12.8, but I didn't want to bump to 2.12.9 due to its regressions. This should be fixed in the next version since I've already bumped to Scala 2.12.10 - https://github.com/sbt/sbt/pull/5072

**Comment by mr-git** [comment]
Oh, that is Scala issue and SBT 1.3.0 uses Scala 2.12.7 internally...
Thanks for details!
Looking forward to get SBT 1.3.1 and to use single JDK again.

(How long we might have to wait?)

**Comment by eed3si9n** [comment]
Hopefully in a few days ~ 1 wk.

**Comment by mr-git** [comment]
@eed3si9n, very much off-topic, but when/if SBT will use Scala 2.13? only at 2.x or possibly sooner?

**Comment by eed3si9n** [comment]
If it's up to me, I would like to keep sbt 1.x + Scala 2.12.x as long as possible (to preserve plugin ecosystem). When 2.12.x starts to fall behind, and plugin authors no longer want to deal with 2.12.x, they would ask for sbt 2.x. Sort of what happened with sbt 0.13 + Scala 2.10.x. That would be when 2.14.x or 3.0.x comes out I'd guess.

**Comment by thea-vik** [comment]
Someone I'm working with keeps getting this error. Can we force SBT to use java 8 or something? We have tried doing this in build.sbt but it did not work.

**Comment by eatkins** [comment]
@torstein-vik can you upgrade to 1.3.3? That version supports jdk 13. Upgrading should be as simple as modifying project/build.properties provided the project already supports 1.3.0.

There are a number of ways to modify which java version sbt uses. You can set the `JAVA_HOME` environment variable to the desired jdk8 location or similarly run `sbt --java-home=$JDK8_HOME`. Other approaches include using https://github.com/shyiko/jabba which allows you to easily switch the default java version used by a given shell session.

**Comment by thea-vik** [comment]
Of course! Thank you so much, this has been bothering us a while :)

**Comment by albertnetymk** [comment]
I see the same error message using sbt 1.3.3 with jdk 13 when trying to build freshly cloned dotty repo. Is this expected?

**Comment by SethTisue** [comment]
@albertnetymk did you change `project/build.properties` in that repo to contain `1.3.3` before running sbt? it's not enough to have sbt 1.3.3 installed systemwide; each repo specifies its own sbt version and that takes precedence

if that's not the issue, it's probably something specific to the Dotty build

**Comment by albertnetymk** [comment]
My bad; once I changed `project/build.properties`, sbt goes beyond that error. I still got compiling errors, `Not found: type IArray`, but I guess it's not related to sbt. Thank you for the help.

**Comment by albertnetymk** [comment]
Since I can't get dotty to work, I went for https://github.com/scala/scala. After a fresh clone, I changed sbt version to 1.3.3 for the following files:

```
project/build.properties
test/benchmarks/project/build.properties
test/jcstress/project/build.properties
```

However, `sbt compile` still gives me the error "java.io.IOError: java.lang.RuntimeException: /packages cannot be represented as URI".

**Comment by SethTisue** [comment]
@albertnetymk getting the scala/scala build to work on sbt 1.3.x and JDK 13 requires a few other changes. let's pursue that here: scala/scala#8525

**Comment by smarter** [comment]
>  I still got compiling errors, Not found: type IArray, but I guess it's not related to sbt. Thank you for the help.

@albertnetymk  I also noticed that error when trying sbt 1.3 with dotty, I've since changed some stuff recently in dotty which should fix this, you could try again with dotty master.

**Comment by albertnetymk** [comment]
I just experimented with dotty of commit `35fbb348c Set baseVersion to 0.22.0`, and sbt 1.3.4.

I still got the error "java.io.IOError: java.lang.RuntimeException: /packages cannot be represented as URI" for command `sbt compile`.

Then, I edited `project/build.properties` to use sbt 1.3.4, and I got `Not found: type IArray` error.

I am using openjdk 13. Am I the only one who experiences this problem?

**Comment by yonghaoy** [comment]
Hi, I am still having the issue with Scala 2.13.1, JDK 13 and sbt 1.3.8. 
I got the same issues when running sbt test:

<details>

<summary>

```
java.lang.RuntimeException: /packages cannot be represented as URI
[error] at java.base/jdk.internal.jrtfs.JrtPath.toUri(JrtPath.java:176)
[error] at scala.tools.nsc.classpath.JrtClassPath.asURLs(DirectoryClassPath.scala:204)
[error] at scala.tools.nsc.classpath.AggregateClassPath.$anonfun$asURLs$1(AggregateClassPath.scala:55)
```

</summary>

```
java.lang.RuntimeException: /packages cannot be represented as URI
[error] at java.base/jdk.internal.jrtfs.JrtPath.toUri(JrtPath.java:176)
[error] at scala.tools.nsc.classpath.JrtClassPath.asURLs(DirectoryClassPath.scala:204)
[error] at scala.tools.nsc.classpath.AggregateClassPath.$anonfun$asURLs$1(AggregateClassPath.scala:55)
[error] at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:240)
[error] at scala.collection.Iterator.foreach(Iterator.scala:937)
[error] at scala.collection.Iterator.foreach$(Iterator.scala:937)
[error] at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
[error] at scala.collection.IterableLike.foreach(IterableLike.scala:70)
[error] at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
[error] at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error] at scala.collection.TraversableLike.flatMap(TraversableLike.scala:240)
[error] at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:237)
[error] at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[error] at scala.tools.nsc.classpath.AggregateClassPath.asURLs(AggregateClassPath.scala:55)
[error] at scala.tools.nsc.typechecker.Macros.findMacroClassLoader(Macros.scala:66)
[error] at scala.tools.nsc.typechecker.Macros.findMacroClassLoader$(Macros.scala:65)
[error] at scala.tools.nsc.Global$$anon$1.findMacroClassLoader(Global.scala:469)
[error] at scala.reflect.macros.runtime.MacroRuntimes.$anonfun$defaultMacroClassloaderCache$2(MacroRuntimes.scala:56)
[error] at scala.reflect.internal.SymbolTable$perRunCaches$$anon$1.apply(SymbolTable.scala:457)
[error] at scala.reflect.macros.runtime.MacroRuntimes.defaultMacroClassloader(MacroRuntimes.scala:58)
[error] at scala.reflect.macros.runtime.MacroRuntimes.defaultMacroClassloader$(MacroRuntimes.scala:58)
[error] at scala.tools.nsc.Global$$anon$1.defaultMacroClassloader(Global.scala:469)
[error] at scala.reflect.macros.runtime.MacroRuntimes$MacroRuntimeResolver.resolveRuntime(MacroRuntimes.scala:76)
[error] at scala.reflect.macros.runtime.MacroRuntimes.$anonfun$standardMacroRuntime$3(MacroRuntimes.scala:38)
[error] at scala.collection.mutable.MapLike.getOrElseUpdate(MapLike.scala:206)
[error] at scala.collection.mutable.MapLike.getOrElseUpdate$(MapLike.scala:203)
[error] at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
[error] at scala.reflect.macros.runtime.MacroRuntimes.standardMacroRuntime(MacroRuntimes.scala:38)
[error] at scala.reflect.macros.runtime.MacroRuntimes.standardMacroRuntime$(MacroRuntimes.scala:31)
[error] at scala.tools.nsc.Global$$anon$1.standardMacroRuntime(Global.scala:469)
[error] at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$14.default(AnalyzerPlugins.scala:448)
[error] at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$14.default(AnalyzerPlugins.scala:445)
[error] at scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:401)
[error] at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroRuntime(AnalyzerPlugins.scala:445)
[error] at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroRuntime$(AnalyzerPlugins.scala:445)
[error] at scala.tools.nsc.Global$$anon$1.pluginsMacroRuntime(Global.scala:469)
[error] at scala.reflect.macros.runtime.MacroRuntimes.macroRuntime(MacroRuntimes.scala:25)
[error] at scala.reflect.macros.runtime.MacroRuntimes.macroRuntime$(MacroRuntimes.scala:25)
[error] at scala.tools.nsc.Global$$anon$1.macroRuntime(Global.scala:469)
[error] at scala.tools.nsc.typechecker.Macros$MacroExpander.$anonfun$expand$1(Macros.scala:619)
[error] at scala.tools.nsc.Global.withInfoLevel(Global.scala:219)
[error] at scala.tools.nsc.typechecker.Macros$MacroExpander.expand(Macros.scala:613)
[error] at scala.tools.nsc.typechecker.Macros$MacroExpander.apply(Macros.scala:600)
[error] at scala.tools.nsc.typechecker.Macros.standardMacroExpand(Macros.scala:764)
[error] at scala.tools.nsc.typechecker.Macros.standardMacroExpand$(Macros.scala:762)
[error] at scala.tools.nsc.Global$$anon$1.standardMacroExpand(Global.scala:469)
[error] at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$12.default(AnalyzerPlugins.scala:432)
[error] at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$12.default(AnalyzerPlugins.scala:429)
[error] at scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:401)
[error] at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand(AnalyzerPlugins.scala:429)
[error] at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand$(AnalyzerPlugins.scala:429)
[error] at scala.tools.nsc.Global$$anon$1.pluginsMacroExpand(Global.scala:469)
[error] at scala.tools.nsc.typechecker.Macros.macroExpand(Macros.scala:757)
[error] at scala.tools.nsc.typechecker.Macros.macroExpand$(Macros.scala:757)
[error] at scala.tools.nsc.Global$$anon$1.macroExpand(Global.scala:469)
[error] at scala.tools.nsc.typechecker.Typers$Typer.vanillaAdapt$1(Typers.scala:1163)
[error] at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1223)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5631)
[error] at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$adapt$1(Typers.scala:881)
[error] at scala.tools.nsc.typechecker.Typers$Typer.adaptToImplicitMethod$1(Typers.scala:471)
[error] at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1219)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5631)
[error] at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedArg$1(Typers.scala:3280)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:471)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typedArgToPoly$1(Typers.scala:3670)
[error] at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$doTypedApply$33(Typers.scala:3678)
[error] at scala.tools.nsc.typechecker.Typers$Typer.handlePolymorphicCall$1(Typers.scala:3678)
[error] at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3689)
[error] at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4767)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4776)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5571)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5617)
[error] at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedArg$1(Typers.scala:3280)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:471)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typedArgToPoly$1(Typers.scala:3670)
[error] at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$doTypedApply$33(Typers.scala:3678)
[error] at scala.tools.nsc.typechecker.Typers$Typer.handlePolymorphicCall$1(Typers.scala:3678)
[error] at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3689)
[error] at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4767)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4776)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5571)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5617)
[error] at scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:5692)
[error] at scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:1079)
[error] at scala.tools.nsc.typechecker.Namers$Namer.valDefSig(Namers.scala:1629)
[error] at scala.tools.nsc.typechecker.Namers$Namer.memberSig(Namers.scala:1798)
[error] at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1763)
[error] at scala.tools.nsc.typechecker.Namers$Namer$ValTypeCompleter.completeImpl(Namers.scala:910)
[error] at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:1960)
[error] at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:1958)
[error] at scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:1953)
[error] at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1530)
[error] at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1678)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5240)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5617)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5681)
[error] at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3264)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3264)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1999)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1868)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5538)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5617)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5681)
[error] at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3264)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3264)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5247)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5540)
[error] at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5617)
[error] at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:106)
[error] at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:441)
[error] at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.run(Analyzer.scala:96)
[error] at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1467)
[error] at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1451)
[error] at scala.tools.nsc.Global$Run.compileSources(Global.scala:1444)
[error] at scala.tools.nsc.Global$Run.compile(Global.scala:1567)
[error] at xsbt.CachedCompiler0.run(CompilerInterface.scala:130)
[error] at xsbt.CachedCompiler0.run(CompilerInterface.scala:105)
[error] at xsbt.CompilerInterface.run(CompilerInterface.scala:31)
[error] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[error] at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
[error] at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
[error] at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
[error] at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error] at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:133)
[error] at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:73)
[error] at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:116)
[error] at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:307)
[error] at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:307)
[error] at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:106)
[error] at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:87)
[error] at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:116)
[error] at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:63)
[error] at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:89)
[error] at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:134)
[error] at sbt.internal.inc.Incremental$.compile(Incremental.scala:80)
[error] at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:67)
[error] at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:311)
[error] at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:269)
[error] at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:159)
[error] at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:238)
[error] at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:69)
[error] at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1544)
[error] at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1518)
[error] at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] at sbt.Execute.work(Execute.scala:278)
[error] at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] at java.base/java.lang.Thread.run(Thread.java:830)
```

</details>

**Comment by SethTisue** [comment]
@yonghaoy how would I reproduce the problem on my own computer?

**Comment by eed3si9n** [comment]
I tried to reproduce this on Travis CI using sbt/io, but I could not - https://travis-ci.org/eed3si9n/io/jobs/653517200

```

$ sdk install java $(sdk list java | grep -o "$ADOPTOPENJDK\.[0-9\.]*hs-adpt" | head -1) || true
$ unset JAVA_HOME
$ java -Xmx32m -version
openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.2+8)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.2+8, mixed mode, sharing)
$ sdk install sbt $TRAVIS_SBT || true
$ sbt -Dsbt.test.fork=true ++$TRAVIS_SCALA212! mimaReportBinaryIssues test
[process_args] java_version = '13'
[sbt_options] declare -a sbt_options='()'
[copyRt] java9_rt = '/home/travis/.sbt/0.13/java9-rt-ext-adoptopenjdk_13_0_2/rt.jar'
Copying runtime jar.
# Executing command line:
java
-Dfile.encoding=UTF-8
-Dsbt.test.fork=true
-Xms1024m
-Xmx1024m
-Xss4M
-XX:ReservedCodeCacheSize=128m
-jar
/home/travis/.sdkman/candidates/sbt/1.3.3/bin/java9-rt-export.jar
/home/travis/.sbt/0.13/java9-rt-ext-adoptopenjdk_13_0_2/rt.jar
# Executing command line:
java
-Dfile.encoding=UTF-8
-Dsbt.test.fork=true
-Xms1024m
-Xmx1024m
-Xss4M
-XX:ReservedCodeCacheSize=128m
-Dscala.ext.dirs=/home/travis/.sbt/0.13/java9-rt-ext-adoptopenjdk_13_0_2
-jar
/home/travis/.sdkman/candidates/sbt/1.3.3/bin/sbt-launch.jar
++2.12.10!
mimaReportBinaryIssues
test
....
[info] Done compiling.
[info] Loading settings for project ioRoot from build.sbt ...
[info]       _     
[info]      (_)___ 
[info]     / / __ \
[info]    / / /_/ /
[info]   /_/\____/ 
[info] Welcome to the build for sbt/io.
[info] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[info]   Java versions is 13. We recommend 1.8.
[info] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by yonghaoy** [comment]
@SethTisue Hi Seth, sorry my bad, I think my repo is using scala 2.12 and that causing issues with JDK13, I am able to make it work by downgrading my jdk to 8.

Thanks

**Comment by SethTisue** [comment]
@yonghaoy what 2.12.x version? 2.12.10 should work. (but yes, downgrading to JDK 8 will also solve it.)

**Comment by yonghaoy** [comment]
@SethTisue I think we are using 2.12.9, don't think we have plan to upgrade it at this moment. Thanks for your help!

**Comment by nerverbe** [comment]
if your pc is mac，check that /usr/local/Cellar/openJdk,
java -version 1.8.0_251
but sbt use the default jdk13

**Comment by nerverbe** [comment]
it's work to me

**Comment by eed3si9n** [comment]
I've put this in https://www.scala-sbt.org/download.html

⚠️ Homebrew maintainers have added a dependency to JDK 13 because they want to use more brew dependencies (https://github.com/Homebrew/homebrew-core/issues/50649). This causes sbt to use JDK 13 even when java available on PATH is JDK 8 or 11. To prevent sbt from running on JDK 13, install [jEnv](https://www.jenv.be/) or switch to using [SDKMAN](https://sdkman.io/).

**Comment by elliotvilhelm** [comment]
If you dont want to deal with this, just downgrade
```
brew install sbt@0.13
echo 'export PATH="/usr/local/opt/sbt@0.13/bin:$PATH"' >> ~/.zshrc
source ~/.zshrc
```

**Comment by eed3si9n** [comment]
`sbt@0.13` would put an old launcher that's no longer supported.

**Comment by SethTisue** [comment]
Although this is the main ticket and #5509 is a duplicate, the clearest statement of where both tickets stand is over at https://github.com/sbt/sbt/issues/5509#issuecomment-729811944
