### ISSUE TITLE
crossTarget should be "scala-${scalaVersion}" when CrossVersion.full

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt#5097]
## steps
sbt version: 1.3.0

```
 > show scalaVersion
[info] 2.12.8
 > show crossTarget
[info] /Users/kenji/some-project/target/scala-2.12
 > set crossVersion := CrossVersion.full
 > show crossTarget
[info] /Users/kenji/some-project/target/scala-2.12
```

## problem

`crossTarget` is `target/scala-2.12` when `crossVersion := CrossVersion.full`

## expectation

`crossTarget` should be `target/scala-2.12.8` when `crossVersion := CrossVersion.full` 🤔 
I think these should not share any `*.class` file caches.

## notes

- https://github.com/sbt/sbt/blob/v1.3.0/main/src/main/scala/sbt/Defaults.scala#L483-L489
- https://github.com/sbt/sbt/blob/v1.3.0/main/src/main/scala/sbt/Defaults.scala#L536-L539

workaround

```scala
  crossTarget := {
    target.value / s"scala-${scalaVersion.value}"
  }
```

**Comment by eed3si9n** [comment]
If `scalaBinaryVersion` is supposed to denote the binary compatibility, in theory, that setting should also be changed but it's probably too late for that. I am fine with just changing `crossTarget` or any other things of this nature.

**Comment by tgodzik** [comment]
@eed3si9n with the crossTarget workaround and a simple project like:
```scala
lazy val root = (project in file(".")).settings(
  inThisBuild(
    List(
      organization := "com.example",
      scalaVersion := "2.12.10"
    )
  ),
  name := "scalatest-example",
  crossTarget := target.value / s"scala-${scalaVersion.value}",
  crossVersion := CrossVersion.full,
  crossScalaVersions := Seq("2.12.9", "2.12.10")
)
```
when doing:
```
++2.12.9
compile
++2.12.10
compile
```
The second compile will remove the classes under 2.12.9 directory. Any idea how to solve that? It causes a lot of additional recompiles.

**Comment by eed3si9n** [comment]
> The second compile will remove the classes under 2.12.9 directory. Any idea how to solve that? It causes a lot of additional recompiles.

We want all of them to recompile if Scala version changes (I think), so it's working as designed.

**Comment by tgodzik** [comment]
@eed3si9n  Shouldn't it be the same situation as with different binary versions?

If I change to 2.11.12, recompile, change back to 2.12.10, not recompilation is done.
However, if I change to 2.12.9 and back, the code is always compiled. 

The target directories are totally separate, so what would be the reason to remove one belonging to a different Scala version? The only common thing here is the input source files, the same as with different binary versions.

**Comment by eed3si9n** [comment]
> The second compile will remove the classes under 2.12.9 directory. Any idea how to solve that? It causes a lot of additional recompiles.

@tgodzik Sorry I didn't read your description carefully earlier. I agree that we need to improve the behavior around transaction class manager, assuming that's doing the deletion.

**Comment by tgodzik** [comment]
@eed3si9n I can try to have this fixed if you point me at the direction? :smiley:

**Comment by eed3si9n** [comment]
The classfile manager code is here - 
https://github.com/sbt/sbt/blob/v1.3.8/main/src/main/scala/sbt/Defaults.scala#L652-L665, which looks ok.

Maybe the culprit is the Analysis file name https://github.com/sbt/sbt/blob/v1.3.8/main/src/main/scala/sbt/Defaults.scala#L606-L614
you could try defining a scripted test scenario like https://github.com/sbt/sbt/tree/develop/sbt/src/sbt-test/actions/cross-incremental, and then maybe try changing the Analysis file name to include the full Scala version.

**Comment by tgodzik** [comment]
Thanks! Will try to fix it.

**Comment by tgodzik** [comment]
@eed3si9n Sorry I haven't managed to take a look at it, but... It's fixed in 1.4.1! So I think we can close it :tada:

**Comment by eed3si9n** [comment]
Some aspects of Zinc may have improved because of virutalization, but overall I think this bug still stands because it's about changing the crossTarget directory.

**Comment by tgodzik** [comment]
Right, but we do change crossTarget directory and it seems that the directories are no longer needlessly removed, so it does look like fixed. How else would this bug show up?

**Comment by eed3si9n** [comment]
The original issue is that sbt should use `target.value / s"scala-${scalaVersion.value}"` out of box when cross is `full`?

**Comment by tgodzik** [comment]
> The original issue is that sbt should use `target.value / s"scala-${scalaVersion.value}"` out of box when cross is `full`?

Ach, my bad! Somehow I thought it's an issue I created. Sorry about that :fearful: !

**Comment by eed3si9n** [comment]
In sbt 2.x target contains full Scala version, so we can probably call this done.
