### ISSUE TITLE
"Can't find bundle for base name" during test using ScalaTest

### ISSUE THREAD

**Issue by rjmac** [sbt/sbt#5262]
## steps
sbt version: 1.3.4

## problem

ScalaTest intermittently fails with a "can't find resource bundle" exception after upgrading to SBT 1.3.4.  This is the same bug as in #5169 but I've got more information.

## expectation

ScalaTest doesn't fail to read its resource bundle.

## notes

This has started happening to our builds too, since upgrading to 1.3.  I've done some digging and this is what I've found.  I haven't managed to make a reliable repro, but I think what I have here shows it's racing with another thread in a fairly small window (the amount of time it takes to read scalatest's resource bundle properties) which is why it's difficult to reproduce.  As in the other bug, our project uses `fork in Test := true`

Here's the relevant part of the stack trace, reversed for annotation purposes, starting from where ScalaTest enters the standard library:

    [error] 	at org.scalatest.Resources$.resourceBundle$lzycompute(Resources.scala:8)
    [error] 	at java.util.ResourceBundle.getBundle(ResourceBundle.java:782)
    [error] 	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1370)
    [error] 	at java.util.ResourceBundle.findBundle(ResourceBundle.java:1436)
    [error] 	at java.util.ResourceBundle.findBundle(ResourceBundle.java:1436)
    [error] 	at java.util.ResourceBundle.findBundle(ResourceBundle.java:1482)
    [error] 	at java.util.ResourceBundle.loadBundle(ResourceBundle.java:1518)
    [error] 	at java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:2704)

`newBundle` is where the stream is opened, a few lines before 2704.  It is acquired from a classloader in the usual `getResource`y ways.

    [error] 	at java.util.PropertyResourceBundle.<init>(PropertyResourceBundle.java:138)

This does nothing with the stream except pass it on to the constructor of `Properties`

    [error] 	at java.util.Properties.load(Properties.java:341)

This wraps the stream in a `LineReader` (a private class within `Properties`) and passes it on.  The constructor of `LineReader` does nothing with the stream except store it in a field.

    [error] 	at java.util.Properties.load0(Properties.java:353)

This actually does things with it: specifically, it repeatedly calls `LineReader.readLine`...

    [error] 	at java.util.Properties$LineReader.readLine(Properties.java:435)

...which reads blocks of bytes out of the stream, which is (some subclass of) `InflaterInputStream`.

    [error] 	at java.io.FilterInputStream.read(FilterInputStream.java:107)
    [error] 	at java.io.FilterInputStream.read(FilterInputStream.java:133)
    [error] 	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:142)
    [error] 	at java.util.zip.InflaterInputStream.ensureOpen(InflaterInputStream.java:67)
    [error] Caused by: java.io.IOException: Stream closed

And finally, this message only happens if _something has actually called `close()` on this stream_.  Merely reaching EOF is not sufficient for this to happen.  As far as I can tell from tracing through the code by hand, nothing in any potential codepath from the open to the exception calls `close` on the stream.  Being an `InflaterInputStream` received from a `ClassLoader`, the best hypothesis I have is that the containing `JarFile` was closed in some other thread, which would have also closed all streams acquired from it, and I can reproduce this behavior by doing that -- getting a resource-stream from a `URLClassLoader`, and then closing that `URLClassLoader` before actually reading from the stream.

And that's where I've gotten stuck.  I can't figure out what's doing the closing, much less why it doesn't realize the scalatest runner isn't done with it yet.  Using `-Dsbt.classloader.close=false`, as mentioned in the other bug, does not prevent this from happening.

**Comment by eed3si9n** [comment]
@rjmac Thanks for the report.

**Comment by eatkins** [comment]
That's a great report.

The `-Dsbt.classloader.close=false` setting is only relevant for non-forked runs so I'm not surprised it didn't help.

**Comment by eatkins** [comment]
What is described in the post points to a possible bug in Scalatest itself since the crash is happening in the forked process which is almost entirely running Scalatest, not sbt code.

**Comment by rjmac** [comment]
Possible, though that opens up other questions -- in the the source of scalatest, I don't see anywhere a classloader gets closed (though enough of scalatest is generated that it's hard to be sure from a grep of the codebase), and merely exiting a jvm when the jar is on the initial classpath doesn't seem to be enough for these symptoms to occur -- or at least, I haven't managed to reproduce it that way.  So it's still a mystery to me what's actually causing the stream to get closed behind the thread's back.

**Comment by rjmac** [comment]
More and more curious... I did a horrible hack to interpose `jdb` between SBT and the `ForkMain` subprocess, and set breakpoints on `URLClassLoader.close` and `ManagedClassLoader.close`.  Neither one of them was hit.  Is it possible that this is happening in the main SBT process and not the child at all, despite the `fork in Test`?  I'm out of time for tonight, but that's the next path I'll go down.

**Comment by rjmac** [comment]
Ok so yes, this seems to be what's happening.  This is all still a bit hypothetical, as I haven't yet gotten a repro with my additional debugging stuff happening, but a classloader which includes `test-classes/`, `classes/`, and all the dependency jars including scalatest is getting closed in the _parent_ process (even with `sbt.classloader.close` set to `false`):

```
	at sbt.internal.ManagedClassLoader.close(ManagedClassLoader.java:99)
	at sbt.Defaults$.close(Defaults.scala:916)
	at sbt.Defaults$.$anonfun$testTasks$12(Defaults.scala:904)
	at sbt.Defaults$.$anonfun$testTasks$12$adapted(Defaults.scala:900)
	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
	at sbt.Execute.work(Execute.scala:290)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

while some other thread is still using it, for what appears to be printing out duration info in a different `CompletionService` call (this stack trace from one of the failures):

```
...
[error] 	at java.util.ResourceBundle.getBundle(ResourceBundle.java:782)
[error] 	at org.scalatest.Resources$.resourceBundle$lzycompute(Resources.scala:8)
[error] 	at org.scalatest.Resources$.resourceBundle(Resources.scala:8)
[error] 	at org.scalatest.Resources$.makeString(Resources.scala:11)
[error] 	at org.scalatest.Resources$.minutesSeconds(Resources.scala:1984)
[error] 	at org.scalatest.tools.StringReporter$.makeDurationString(StringReporter.scala:1083)
[error] 	at org.scalatest.tools.StringReporter$.summaryFragments(StringReporter.scala:252)
[error] 	at org.scalatest.tools.Framework$ScalaTestRunner.done(Framework.scala:750)
[error] 	at sbt.Defaults$.$anonfun$allTestGroupsTask$11(Defaults.scala:1226)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[error] 	at scala.collection.immutable.Map$Map3.foreach(Map.scala:195)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] 	at sbt.Defaults$.$anonfun$allTestGroupsTask$5(Defaults.scala:1224)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
...
```

This starts to hang together, I think.  Is it possible that these two `CompletionService` calls can happen in a nondeterministic or concurrent order, and if they do where exactly is the bug that assumes an ordering between them -- in SBT or in ScalaTest?

**Comment by eed3si9n** [comment]
@rjmac Thanks for the detective work!

https://github.com/sbt/sbt/blob/v1.3.4/main/src/main/scala/sbt/Defaults.scala#L1226 says:

```scala
            Tests.Summary(frameworks(tf).name, r.done())
```

so that's sbt's Defaults trying to print out the name of the test framework that's blowing up? If so, the primary suspect might be sbt closing the classsloader too early, or not caching the name before closing it?

**Comment by rjmac** [comment]
From the stack trace, it looks like it's the `r.done()` call that's blowing up, not the name part.  But yes, it looks like SBT is sometimes closing the classloader too early.

**Comment by eed3si9n** [comment]
Could you describe the reproduction steps?

```scala
    test := {
      val trl = (testResultLogger in (Test, test)).value
      val taskName = Project.showContextKey(state.value).show(resolvedScoped.value)
      try trl.run(streams.value.log, executeTests.value, taskName)
      finally close(testLoader.value)
    },
```

`test` task in theory should not close the classloader until the tests (and summary printing) are done.

**Comment by rjmac** [comment]
I haven't nailed down repro steps completely, but in the case where it's occuring:
* `fork in Test` is true
* There are several subprojects
Given that, `sbt test` will, some small fraction of the time, fail in this way.  It doesn't always fail in the same subproject.

Could `testLoader`'s value be getting shared among different subprojects?  I'm not yet sure whether having subprojects is a necessary condition or just makes the timing work out so it's easier to hit the window.

**Comment by eed3si9n** [comment]
As far as I know, each subproject is given a fresh layered classloader in https://github.com/sbt/sbt/blob/v1.3.4/main/src/main/scala/sbt/internal/ClassLoaders.scala#L36-L60

**Comment by rjmac** [comment]
I've got a repro!  It is not a _reliable_ one, but it has happened at least once on my machine: https://github.com/rjmac/sbt-5262 - I just let that run for a while with `while sbt test; do true; done` and after quite a while it failed.

The case where it failed its output was:

```
[info] Loading project definition from /home/robertm/closetest2/project
[info] Loading settings for project closetest2 from build.sbt ...
[info] Set current project to closetest2 (in build file:/home/robertm/closetest2/)
[info] Run completed in 704 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] No tests were executed.
[info] Run completed in 634 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] No tests were executed.
[info] Run completed in 655 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] No tests were executed.
[info] Run completed in 435 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] No tests were executed.
[info] Run completed in 486 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] No tests were executed.
[info] Run completed in 239 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] No tests were executed.
[info] Run completed in 756 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] No tests were executed.
[info] Run completed in 41 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] No tests were executed.
[info] ATest:
[info] - a test
[info] Run completed in 2 seconds, 232 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[error] java.util.MissingResourceException: Can't find bundle for base name org.scalatest.ScalaTestBundle, locale en_US
[error] 	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581)
[error] 	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
[error] 	at java.util.ResourceBundle.getBundle(ResourceBundle.java:782)
[error] 	at org.scalatest.Resources$.resourceBundle$lzycompute(Resources.scala:8)
[error] 	at org.scalatest.Resources$.resourceBundle(Resources.scala:8)
[error] 	at org.scalatest.Resources$.makeString(Resources.scala:11)
[error] 	at org.scalatest.Resources$.milliseconds(Resources.scala:1932)
[error] 	at org.scalatest.tools.StringReporter$.makeDurationString(StringReporter.scala:1063)
[error] 	at org.scalatest.tools.StringReporter$.summaryFragments(StringReporter.scala:254)
[error] 	at org.scalatest.tools.Framework$ScalaTestRunner.done(Framework.scala:773)
[error] 	at sbt.Defaults$.$anonfun$allTestGroupsTask$11(Defaults.scala:1226)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[error] 	at scala.collection.immutable.Map$Map1.foreach(Map.scala:128)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] 	at sbt.Defaults$.$anonfun$allTestGroupsTask$5(Defaults.scala:1224)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.util.zip.ZipException: ZipFile closed
[error] 	at java.util.zip.ZipFile.ensureOpenOrZipException(ZipFile.java:696)
[error] 	at java.util.zip.ZipFile.access$1300(ZipFile.java:60)
[error] 	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:733)
[error] 	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:434)
[error] 	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
[error] 	at java.io.FilterInputStream.read(FilterInputStream.java:133)
[error] 	at java.io.FilterInputStream.read(FilterInputStream.java:107)
[error] 	at java.util.Properties$LineReader.readLine(Properties.java:435)
[error] 	at java.util.Properties.load0(Properties.java:353)
[error] 	at java.util.Properties.load(Properties.java:341)
[error] 	at java.util.PropertyResourceBundle.<init>(PropertyResourceBundle.java:138)
[error] 	at java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:2704)
[error] 	at java.util.ResourceBundle.loadBundle(ResourceBundle.java:1518)
[error] 	at java.util.ResourceBundle.findBundle(ResourceBundle.java:1482)
[error] 	at java.util.ResourceBundle.findBundle(ResourceBundle.java:1436)
[error] 	at java.util.ResourceBundle.findBundle(ResourceBundle.java:1436)
[error] 	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1370)
[error] 	at java.util.ResourceBundle.getBundle(ResourceBundle.java:782)
[error] 	at org.scalatest.Resources$.resourceBundle$lzycompute(Resources.scala:8)
[error] 	at org.scalatest.Resources$.resourceBundle(Resources.scala:8)
[error] 	at org.scalatest.Resources$.makeString(Resources.scala:11)
[error] 	at org.scalatest.Resources$.milliseconds(Resources.scala:1932)
[error] 	at org.scalatest.tools.StringReporter$.makeDurationString(StringReporter.scala:1063)
[error] 	at org.scalatest.tools.StringReporter$.summaryFragments(StringReporter.scala:254)
[error] 	at org.scalatest.tools.Framework$ScalaTestRunner.done(Framework.scala:773)
[error] 	at sbt.Defaults$.$anonfun$allTestGroupsTask$11(Defaults.scala:1226)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[error] 	at scala.collection.immutable.Map$Map1.foreach(Map.scala:128)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] 	at sbt.Defaults$.$anonfun$allTestGroupsTask$5(Defaults.scala:1224)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (p3 / Test / executeTests) java.util.MissingResourceException: Can't find bundle for base name org.scalatest.ScalaTestBundle, locale en_US
[error] Total time: 7 s, completed Dec 5, 2019 2:59:25 PM
```

It is interesting to me that the case where it failed it did the one subproject that actually had a test last.  Going to walk down that path a bit and see where it leads...

**Comment by eatkins** [comment]
To speed up the repro, you might want to try adding:
```scala
import complete.Parser._
import complete.Parsers._
commands +=
  Command("repeat")(s => Space.+ ~> (IntBasic <~ Space.+) ~ matched(s.combinedParser)) {
    case (s, (i, cmd)) => (1 until i).foldLeft(cmd :: s) { case (st, _) => cmd :: st }
  }
```

to the build.sbt and then you could do `sbt repeat 1000 test` or something like that. It's possible that it won't actually fail if the sbt session persists between runs though.

**Comment by eatkins** [comment]
I just reproduced with the repeat command and your repro project.

**Comment by eatkins** [comment]
Ok. I think I understand what is happening. If one project closes its classloader while another project is reading the property files from the scalatest jar, it closes the underlying jarfile out from underneath the active project. I can think of two obvious ways to fix this: copy the classpath ala `run` or put the known test framework jars in a separate classloader layer between the scala library and the rest of the classpath. We also could stop closing the classloaders (or at least make `-Dsbt.classloader.close=false` actually prevent the loaders from being closed like it used to).

I was able to reproduce with fork := false as well. It comes down to the timing of when the projects finish running. The repro project has 10 identical projects so they tend to induce the bug since test takes about the same amount of time for each project.

**Comment by eed3si9n** [comment]
Continuing from https://github.com/sbt/sbt/pull/5273#discussion_r355062591 

I wonder if this could also happen to things like Akka where you have some common library that is used across multiple subprojects. I've heard of reports recently that might be related:


> Uncaught error from thread [application-akka.actor.default-dispatcher-22]: loader (instance of sbt/internal/ManagedClassLoader$ZombieClassLoader): attempted duplicate class definition for name: "akka/io/Tcp$CloseCommand", shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.LinkageError: loader (instance of sbt/internal/ManagedClassLoader$ZombieClassLoader): attempted duplicate class definition for name: "akka/io/Tcp$CloseCommand"


The error message says "attempted duplicate class definition for name" similar to https://github.com/sbt/sbt/issues/5249, but this one is `akka/io/Tcp$CloseCommand`, which is not part of JDK.

**Comment by eatkins** [comment]
That looks like https://github.com/sbt/sbt/pull/5267.

**Comment by eed3si9n** [comment]
This is fixed in https://github.com/sbt/sbt/pull/5273

**Comment by dwijnand** [comment]
Also #5327.

**Comment by kiara-riley** [comment]
Hey @eed3si9n @eatkins I am still seeing this issue(or something very very similar) with all the latest libraries. 

Here is my updated repro repo based on the original. Notably, I added the test file to all 10 projects, added Ethans helpful command, an alias for `;clean;test` and updated the library versions. I run it in this way: `time sbt "repeat 1000 testAndClean"`, and it takes about 5-10 minutes sometimes longer on my machine. 

https://github.com/kraigmckernan/sbt-5262

```
[error] /home/kmckernan/git/sbt-5262/p4/src/test/scala/closetest/ATest.scala:6:5: exception during macro expansion: 
[error] java.util.MissingResourceException: Can't find bundle for base name org.scalactic.ScalacticBundle, locale en_US
[error]         at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581)
[error]         at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
[error]         at java.util.ResourceBundle.getBundle(ResourceBundle.java:782)
[error]         at org.scalactic.Resources$.resourceBundle$lzycompute(Resources.scala:8)
[error]         at org.scalactic.Resources$.resourceBundle(Resources.scala:8)
[error]         at org.scalactic.Resources$.pleaseDefineScalacticFillFilePathnameEnvVar(Resources.scala:256)
[error]         at org.scalactic.source.PositionMacro$PositionMacroImpl.apply(PositionMacro.scala:65)
[error]         at org.scalactic.source.PositionMacro$.genPosition(PositionMacro.scala:85)
[error]     1 should be (1)
[error]     ^
```

Do you guys have any ideas here? I can't upgrade to `1.3` if my CI will fail every few runs on my large project.

I don't think the change to set `sbt.classloader.close` to `false` by default is a complete fix for this.

Interestingly I was also able to reproduce the problem in sbt `1.3.5` even though there is some custom code for a scalatest classloader.

**Comment by eed3si9n** [comment]
@kraigmckernan Looks like you're hitting similar issue during compilation since it's an error coming from a macro. I'll create a new issue for this until we find out it's the same issue.
