### ISSUE TITLE
Sbt state resets with every task when StateTransform tasks are run sequentially.

### ISSUE THREAD

**Issue by alexFrankfurt** [sbt/sbt#5453]
## steps
Create project with following build:
build.properties
```sbt
sbt.version = 1.3.8
```
build.sbt
```sbt
name := "initial"

scalaVersion := "2.12.10"

lazy val changeName = taskKey[StateTransform]("Changes project name")

lazy val changeScalaVersion = taskKey[StateTransform]("Changes scala version")

changeName := {
  val st = state.value
  val extracted = Project.extract(st)
  new StateTransform(extracted.appendWithSession(Seq(name := "changed-name"), st))
}

changeScalaVersion := {
  val st = state.value
  val extracted = Project.extract(st)
  new StateTransform(extracted.appendWithSession(Seq(scalaVersion := "2.13.1"), st))
}

```
or clone https://github.com/alexFrankfurt/sbt-ex2

1. start sbt from terminal
2. run `changeName`
3. run `changeScalaVersion`

## problem

After running `changeScalaVersion` state modifications of `changeName` vanish.
`name = initial; scalaVersion = 2.13.1`

## expectation

State changes of `changeScalaVersion` applied after changes of `changeName` and accumulate.
`name = changed-name; scalaVersion = 2.13.1`

## notes
Current behaviour:
![state-transform](https://user-images.githubusercontent.com/11091671/75691636-61ed5080-5cb5-11ea-8555-d003be86e5d1.png)

**Comment by eed3si9n** [comment]
I think this was fixed in https://github.com/sbt/sbt/pull/5260 (https://github.com/sbt/sbt/pull/5260/commits/a83c280db123f814d5fd21a634017361fb83372d), and it will be part of sbt 1.4.0.

**Comment by alexFrankfurt** [comment]
I have updated [example](https://github.com/alexFrankfurt/sbt-ex2) to the latest nightly build (1.4.0-bin-20200213T192557). But problem persists.
![state-1 4](https://user-images.githubusercontent.com/11091671/75758890-ba6c2e80-5d45-11ea-93f9-8ca981859205.png)

**Comment by eed3si9n** [comment]
Did you switch to using StateTransform as a wrapper for `State => State`?

**Comment by alexFrankfurt** [comment]
Yes, I wrapped all code inside lambda argument to constructor.
```scala

name := "initial"

scalaVersion := "2.12.10"

lazy val changeName = taskKey[StateTransform]("Changes project name")

lazy val changeScalaVersion = taskKey[StateTransform]("Changes scala version")

changeName := {
  StateTransform((s: State) => {
    val extracted = Project.extract(s)
    extracted.appendWithSession(Seq(name := "changed-name"), s)
  })
}

changeScalaVersion := {
  StateTransform((s: State) => {
    val extracted = Project.extract(s)
    extracted.appendWithSession(Seq(scalaVersion := "2.13.1"), s)
  })
}
```

**Comment by eatkins** [comment]
I'm looking at this. FYI, you don't need a leading semicolon anymore for multi commands: `name; scalaVersion` works.

**Comment by eatkins** [comment]
This isn't actually an issue with `StateTransform`, it's an issue with `Extracted.appendWithSession`. I'm closing this in favor of #5459.
