### ISSUE TITLE
Sbt recompiling unchanged files every time because of modified binary dependency

### ISSUE THREAD

**Issue by everson** [sbt/sbt#583]
```
[debug] Modified binary dependencies:
Set(/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/lib/jce.jar)
```

It happens every times in a sbt session compile task is called. Even if called after a clean and ten times in a row.

the jce.jar file is untouched. 

Stackoverflow question about this issue: http://stackoverflow.com/questions/12972183/sbt-always-does-full-rebuild-because-of-modified-binary-dependency-rt-jar

**Comment by harrah** [comment]
Fixed by #584.

**Comment by everson** [comment]
I am still getting this issue. Here is what I did, please let me know if I missed something:
1.   git clone git://github.com/harrah/xsbt.git
2.   git checkout v0.12.1
3.   applied patch to Incremental.scala
4.   sbt build-all ( Built OK)
5.   cp /usr/local/bin/sbt to /usr/local/bin/xsbt, updating jar to <xsbt>/target/sbt-launch-0.12.1.jar
6.   ran xsbt
7.   $ clean
8.   $ compile
9.   $ compile
10. rm -rf ~/.sbt/boot/*
11. repeat 6-9

Between #8 and #9, I wasn't expecting to get anything compiled again, yet:

[debug] Modified binary dependencies: Set(/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/lib/jce.jar)

**Comment by harrah** [comment]
Using the same version as a stable release will confuse caches everywhere.  Bump the version to 0.12.2-SNAPSHOT or similar.

**Comment by everson** [comment]
Great. Solved. Many thanks.
