### ISSUE TITLE
"sbt doc" fail with sbt 1.4.0 and dotty

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt#5927]
## steps

https://github.com/xuwei-k/sbt-1.4.0-dotty-doc/commit/7dff281aa1872de1efebb234971e90f6aaa9ac6f

### build.sbt

```scala
scalaVersion := "0.27.0-RC1"
```

### project/build.properties

```
sbt.version=1.4.0
```

### project/plugins.sbt

```scala
addSbtPlugin("ch.epfl.lamp" % "sbt-dotty" % "0.4.2")
```

### Main.scala

```scala
package example

object Main
```

run: `sbt doc`

## problem

https://github.com/xuwei-k/sbt-1.4.0-dotty-doc/runs/1207499336

```
[info] Main Scala API documentation to /home/runner/work/sbt-1.4.0-dotty-doc/sbt-1.4.0-dotty-doc/target/scala-0.27/api...
Compiling (1/1): Main.class
[doc info] Generating doc page for: example
[doc warn] the specified `/api` directory will not be used since it is needed for the api documentation
[doc info] Generating doc page for: example.Main$
[doc info] Generating doc page for: example.Main$
Error:  java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
Error:  	at xsbt.DottydocRunner.run(DottydocRunner.java:85)
Error:  	at xsbt.ScaladocInterface.run(ScaladocInterface.java:11)
Error:  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Error:  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:  	at java.lang.reflect.Method.invoke(Method.java:498)
Error:  	at sbt.internal.inc.AnalyzingCompiler.invoke(AnalyzingCompiler.scala:330)
Error:  	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:176)
Error:  	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:134)
Error:  	at sbt.Doc$.$anonfun$scaladoc$1(Doc.scala:52)
Error:  	at sbt.Doc$.$anonfun$scaladoc$1$adapted(Doc.scala:40)
Error:  	at sbt.RawCompileLike$.$anonfun$prepare$1(RawCompileLike.scala:79)
Error:  	at sbt.RawCompileLike$.$anonfun$prepare$1$adapted(RawCompileLike.scala:72)
Error:  	at sbt.RawCompileLike$.$anonfun$cached$4(RawCompileLike.scala:63)
Error:  	at sbt.RawCompileLike$.$anonfun$cached$4$adapted(RawCompileLike.scala:61)
Error:  	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
Error:  	at sbt.RawCompileLike$.$anonfun$cached$1(RawCompileLike.scala:68)
Error:  	at sbt.RawCompileLike$.$anonfun$cached$1$adapted(RawCompileLike.scala:52)
Error:  	at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1944)
Error:  	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
Error:  	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
Error:  	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
Error:  	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
Error:  	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
Error:  	at sbt.Execute.work(Execute.scala:291)
Error:  	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
Error:  	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
Error:  	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
Error:  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Error:  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Error:  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Error:  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Error:  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Error:  	at java.lang.Thread.run(Thread.java:748)
Error:  Caused by: java.lang.reflect.InvocationTargetException
Error:  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Error:  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:  	at java.lang.reflect.Method.invoke(Method.java:498)
Error:  	at xsbt.DottydocRunner.run(DottydocRunner.java:81)
Error:  	at xsbt.ScaladocInterface.run(ScaladocInterface.java:11)
Error:  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Error:  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:  	at java.lang.reflect.Method.invoke(Method.java:498)
Error:  	at sbt.internal.inc.AnalyzingCompiler.invoke(AnalyzingCompiler.scala:330)
Error:  	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:176)
Error:  	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:134)
Error:  	at sbt.Doc$.$anonfun$scaladoc$1(Doc.scala:52)
Error:  	at sbt.Doc$.$anonfun$scaladoc$1$adapted(Doc.scala:40)
Error:  	at sbt.RawCompileLike$.$anonfun$prepare$1(RawCompileLike.scala:79)
Error:  	at sbt.RawCompileLike$.$anonfun$prepare$1$adapted(RawCompileLike.scala:72)
Error:  	at sbt.RawCompileLike$.$anonfun$cached$4(RawCompileLike.scala:63)
Error:  	at sbt.RawCompileLike$.$anonfun$cached$4$adapted(RawCompileLike.scala:61)
Error:  	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
Error:  	at sbt.RawCompileLike$.$anonfun$cached$1(RawCompileLike.scala:68)
Error:  	at sbt.RawCompileLike$.$anonfun$cached$1$adapted(RawCompileLike.scala:52)
Error:  	at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1944)
Error:  	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
Error:  	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
Error:  	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
Error:  	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
Error:  	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
Error:  	at sbt.Execute.work(Execute.scala:291)
Error:  	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
Error:  	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
Error:  	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
Error:  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Error:  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Error:  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Error:  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Error:  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Error:  	at java.lang.Thread.run(Thread.java:748)
Error:  Caused by: java.nio.file.FileSystemException: /home/runner/work/sbt-1.4.0-dotty-doc/sbt-1.4.0-dotty-doc/project/target/sbt-load.sock: No such device or address
Error:  	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
Error:  	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
Error:  	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
Error:  	at sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:230)
Error:  	at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:581)
Error:  	at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
Error:  	at java.nio.file.Files.copy(Files.java:1274)
Error:  	at dotty.tools.dottydoc.staticsite.Site.copyStaticFiles$$anonfun$2$$anonfun$1(Site.scala:140)
Error:  	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
Error:  	at dotty.tools.dottydoc.staticsite.Site.copyStaticFiles$$anonfun$1(Site.scala:140)
Error:  	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
Error:  	at dotty.tools.dottydoc.staticsite.Site.createOutput(Site.scala:187)
Error:  	at dotty.tools.dottydoc.staticsite.Site.copyStaticFiles(Site.scala:169)
Error:  	at dotty.tools.dottydoc.DocDriver.generateSite$1(DocDriver.scala:65)
Error:  	at dotty.tools.dottydoc.DocDriver.process(DocDriver.scala:69)
Error:  	at dotty.tools.dottydoc.Main.process(Main.scala)
Error:  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Error:  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:  	at java.lang.reflect.Method.invoke(Method.java:498)
Error:  	at xsbt.DottydocRunner.run(DottydocRunner.java:81)
Error:  	at xsbt.ScaladocInterface.run(ScaladocInterface.java:11)
Error:  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Error:  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:  	at java.lang.reflect.Method.invoke(Method.java:498)
Error:  	at sbt.internal.inc.AnalyzingCompiler.invoke(AnalyzingCompiler.scala:330)
Error:  	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:176)
Error:  	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:134)
Error:  	at sbt.Doc$.$anonfun$scaladoc$1(Doc.scala:52)
Error:  	at sbt.Doc$.$anonfun$scaladoc$1$adapted(Doc.scala:40)
Error:  	at sbt.RawCompileLike$.$anonfun$prepare$1(RawCompileLike.scala:79)
Error:  	at sbt.RawCompileLike$.$anonfun$prepare$1$adapted(RawCompileLike.scala:72)
Error:  	at sbt.RawCompileLike$.$anonfun$cached$4(RawCompileLike.scala:63)
Error:  	at sbt.RawCompileLike$.$anonfun$cached$4$adapted(RawCompileLike.scala:61)
Error:  	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
Error:  	at sbt.RawCompileLike$.$anonfun$cached$1(RawCompileLike.scala:68)
Error:  	at sbt.RawCompileLike$.$anonfun$cached$1$adapted(RawCompileLike.scala:52)
Error:  	at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1944)
Error:  	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
Error:  	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
Error:  	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
Error:  	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
Error:  	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
Error:  	at sbt.Execute.work(Execute.scala:291)
Error:  	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
Error:  	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
Error:  	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
Error:  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Error:  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Error:  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Error:  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Error:  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Error:  	at java.lang.Thread.run(Thread.java:748)
Error:  (Compile / doc) java.lang.reflect.InvocationTargetException
Error:  Total time: 6 s, completed Oct 5, 2020 5:52:37 AM
Error: Process completed with exit code 1.
```

**Comment by smarter** [comment]
Fixed in https://github.com/lampepfl/dotty/pull/9756

**Comment by eed3si9n** [comment]
@xuwei-k Thanks for the report, and @smarter thanks for the fix.

**Comment by thesamet** [comment]
This issue still occurs with sbt-dotty 0.4.5 (exception below). Is the fix going to be part of of the next version of sbt-dotty or a different fix needs to be applied?
```
Caused by: java.nio.file.FileSystemException: /home/runner/work/ScalaPB/ScalaPB/project/target/sbt-load.sock: No such device or address
Error:  	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
Error:  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
Error:  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
Error:  	at java.base/sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:235)
Error:  	at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:603)
Error:  	at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:258)
Error:  	at java.base/java.nio.file.Files.copy(Files.java:1297)
Error:  	at dotty.tools.dottydoc.staticsite.Site.copyStaticFiles$$anonfun$2$$anonfun$1(Site.scala:140)
Error:  	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
Error:  	at dotty.tools.dottydoc.staticsite.Site.copyStaticFiles$$anonfun$1(Site.scala:140)
Error:  	at dotty.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
Error:  	at dotty.tools.dottydoc.staticsite.Site.createOutput(Site.scala:187)
Error:  	at dotty.tools.dottydoc.staticsite.Site.copyStaticFiles(Site.scala:169)
Error:  	at dotty.tools.dottydoc.DocDriver.generateSite$1(DocDriver.scala:65)
Error:  	at dotty.tools.dottydoc.DocDriver.process(DocDriver.scala:69)
Error:  	at dotty.tools.dottydoc.Main.process(Main.scala)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Error:  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
Error:  	at xsbt.DottydocRunner.run(DottydocRunner.java:81)
Error:  	at xsbt.ScaladocInterface.run(ScaladocInterface.java:11)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Error:  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
Error:  	at sbt.internal.inc.AnalyzingCompiler.invoke(AnalyzingCompiler.scala:330)
Error:  	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:176)
Error:  	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:134)
Error:  	at sbt.Doc$.$anonfun$scaladoc$1(Doc.scala:52)
Error:  	at sbt.Doc$.$anonfun$scaladoc$1$adapted(Doc.scala:40)
Error:  	at sbt.RawCompileLike$.$anonfun$prepare$1(RawCompileLike.scala:79)
Error:  	at sbt.RawCompileLike$.$anonfun$prepare$1$adapted(RawCompileLike.scala:72)
Error:  	at sbt.RawCompileLike$.$anonfun$cached$4(RawCompileLike.scala:63)
Error:  	at sbt.RawCompileLike$.$anonfun$cached$4$adapted(RawCompileLike.scala:61)
Error:  	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
Error:  	at sbt.RawCompileLike$.$anonfun$cached$1(RawCompileLike.scala:68)
Error:  	at sbt.RawCompileLike$.$anonfun$cached$1$adapted(RawCompileLike.scala:52)
Error:  	at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1944)
Error:  	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
Error:  	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
Error:  	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
Error:  	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
Error:  	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
Error:  	at sbt.Execute.work(Execute.scala:291)
Error:  	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
Error:  	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
Error:  	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
Error:  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Error:  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
Error:  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Error:  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Error:  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Error:  	at java.base/java.lang.Thread.run(Thread.java:835)
```

**Comment by smarter** [comment]
The fix is part of dotty itself, not sbt-dotty, you need a recent nightly or to wait until 3.0.0-M1 is out (next week)
