### ISSUE TITLE
sbt SNAPSHOT dependency with classifiers not updating

### ISSUE THREAD

**Issue by mvfranz** [sbt/sbt#641]
I have a dependency on two jars, one with a classifier and one without.  When a new SNAPSHOT version is published the jar with the classifier is not updated in my local Ivy cache.

Steps to reproduce:
1. setup my project dependency
libraryDependencies += "group" %% "artifactA" % "1.0.0-SNAPSHOT" withSources() classifier("test") classifier("")
2. sbt update -- project is updated and both the jars are downloaded
3. publish a new version of 'artifactA' (a different project)
4. sbt update -- updated my project that has a dependency on 'artifactA'

The result is that group-artifactA_2.9.1-1.0.0-SNAPSHOT.jar is updated, but group-artifactA_2.9.1-1.0.0-SNAPSHOT-test.jar is not.  

The expected result is that both jars are updated:
- group-artifactA_2.9.1-1.0.0-SNAPSHOT.jar
- group-artifactA_2.9.1-1.0.0-SNAPSHOT-test.jar

I have been using sbt 0.12.1.  This issue has also been confirmed to to exist in 0.12.2-RC2 and the 0.13 branch.

**Comment by harrah** [comment]
Fixed in 0f28164b53c2e68f39036c602c9a71836c4be017.

**Comment by greenrd** [comment]
I am still experiencing this issue on sbt 0.13.0. Please reopen this issue. My dependencies look like this:

```
      "com.example.foo" %% "bar" % "0-SNAPSHOT",
      "com.example.foo" %% "bar" % "0-SNAPSHOT" % "test" classifier "test" classifier "" excludeAll(ExclusionRule(organization = "org.scalaz")),
```

I can't remember why I had to specify the main dependency twice, but I had to, in the past.

**Comment by greenrd** [comment]
Apologies - the problem was actually that sbt 0.13.0 now generates test jars with classifier "tests", not "test".

**Comment by tarasshpek** [comment]
Hi guys. I can reproduce this bug in 0.13.5.

**Comment by davidainslie** [comment]
Also does not work in 0.13.8

**Comment by benjaminparker** [comment]
Doesn't work for me either in 0.13.8

**Comment by eed3si9n** [comment]
Does anyone have a automated repro steps for the regression?
I couldn't reproduce it in b1aa263b7f281496960e1bcf3534406e068277e5

**Comment by dwijnand** [comment]
I guess we can keep this closed and work on this in #1676. Note that the fix here was reverted in #1234 for a number of reasons.

**Comment by nik-kashi** [comment]
This problem still exists in latest version
`sbt.version=0.13.11`

and in my build.sbt :

```
libraryDependencies ++= Seq(
...
"com.rh.cores" % "treasury" % treasuryVer changing(),
  "com.rh.cores" % "treasury" % treasuryVer % Test classifier "tests" changing(),
...
```

but after executing `sbt update` only main dependencies updated and "tests" classified  dependencies does not update.
I should remove them manually from .ivy2 folder

**Note that the version is snapshot**

**Comment by barrybecker4** [comment]
I think that this issue should be reopened. The problem is reproducible using sbt version 0.13.7.
Here is the dependency in my sbt file:
 `"org.apache.spark" % "spark-mdlp-discretization_2.11" % "0.2-SNAPSHOT" changing(),`
I have tried repeatedly to get the latest SNAPSHOT using "sbt update" but it does not pull it unless I explicitly removed the existing spark-mdlp-discretization_2.11-0.2-SNAPSHOT.jar from 
~/.ivy2/cache/org.apache.spark/spark-mdlp-discretization_2.11/jars

I will try again with the latest version of sbt, but I am not hopeful given above post.

**Comment by barrybecker4** [comment]
OK. I tried again with 0.13.12 and it seemed to work, so never mind...
