### ISSUE TITLE
sbt launcher - error retrieving required libraries for SBT 0.x

### ISSUE THREAD

**Issue by miron89** [sbt/sbt#7523]
## steps

Create dummy SBT project that use SBT version 0.13.16 (also tested on 0.13.17 & 0.13.18)
Using the latest SBT launcher 1.9.9 try to enter SBT shell or build the project

## problem

Running the following inside Docker container:
```
RUN curl -L https://www.scala-sbt.org/sbt-rpm.repo > /etc/yum.repos.d/sbt-rpm.repo \
    && yum install -y sbt \
    && sbt ";dist"
```
Failed with:

UNRESOLVED DEPENDENCIES:
- org.scala-sbt#actions;0.13.16: not found
- org.scala-sbt#main-settings;0.13.16: not found
- org.scala-sbt#ivy;0.13.16: not found
- org.scala-sbt#process;0.13.16: not found
- org.scala-sbt#relation;0.13.16: not found
- org.scala-sbt#run;0.13.16: not found
- org.scala-sbt#command;0.13.16: not found
- org.scala-sbt#compiler-interface;0.13.16: not found
- org.scala-sbt#sbt;0.13.16: not found

[error] [launcher] error during sbt launcher: error retrieving required libraries
[error] [launcher] could not retrieve sbt 0.13.16

## expectation

SBT 0.x works

## notes

I was able to reproduce on multiple 0.x versions
The issue cannot be reproduced with SBT 1.x
The issue started in the last 2 days so it feels like something have changed

**Comment by SethTisue** [comment]
seems to not be a simple repeat of https://github.com/sbt/sbt/issues/7202 , since e.g. `curl -O -L https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.dwijnand/sbt-dynver/scala_2.12/sbt_1.0/4.1.1/jars/sbt-dynver.jar` succeeds

**Comment by SethTisue** [comment]
```
% curl -f -O -L 'https://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/command/0.13.16/command-0.13.16.pom'
...
curl: (22) The requested URL returned error: 404
```

**Comment by SethTisue** [comment]
full log

I would try to reproduce it with `curl`, except I don't actually know which of these URLs are the correct ones that would be expected to succeed. anyway since I'm able to reproduce it it seems there really is some problem with the hosting

```
[info] [launcher] getting org.scala-sbt sbt 0.13.16  (this may take some time)...
:: loading settings :: url = jar:file:/opt/homebrew/Cellar/sbt/1.9.9/libexec/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: loading settings :: url = jar:file:/opt/homebrew/Cellar/sbt/1.9.9/libexec/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: loading settings :: url = jar:file:/opt/homebrew/Cellar/sbt/1.9.9/libexec/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: loading settings :: url = jar:file:/opt/homebrew/Cellar/sbt/1.9.9/libexec/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: loading settings :: url = jar:file:/opt/homebrew/Cellar/sbt/1.9.9/libexec/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: loading settings :: url = jar:file:/opt/homebrew/Cellar/sbt/1.9.9/libexec/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: loading settings :: url = jar:file:/opt/homebrew/Cellar/sbt/1.9.9/libexec/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: loading settings :: url = jar:file:/opt/homebrew/Cellar/sbt/1.9.9/libexec/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: loading settings :: url = jar:file:/opt/homebrew/Cellar/sbt/1.9.9/libexec/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: loading settings :: url = jar:file:/opt/homebrew/Cellar/sbt/1.9.9/libexec/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: loading settings :: url = jar:file:/opt/homebrew/Cellar/sbt/1.9.9/libexec/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: loading settings :: url = jar:file:/opt/homebrew/Cellar/sbt/1.9.9/libexec/bin/sbt-launch.jar!/org/apache/ivy/core/settings/ivysettings.xml
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/control/0.13.16/jars/control.jar ...
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/collections/0.13.16/jars/collections.jar ...
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/persist/0.13.16/jars/persist.jar ...
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/api/0.13.16/jars/api.jar ...
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.16/jars/main.jar ...
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.16/jars/sbt.jar ...
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/classfile/0.13.16/jars/classfile.jar ...
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/io/0.13.16/jars/io.jar ...
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main-settings/0.13.16/jars/main-settings.jar ...
	[SUCCESSFUL ] org.scala-sbt#control;0.13.16!control.jar (2097ms)
	[SUCCESSFUL ] org.scala-sbt#classfile;0.13.16!classfile.jar (1905ms)
	[SUCCESSFUL ] org.scala-sbt#persist;0.13.16!persist.jar (2522ms)
	[SUCCESSFUL ] org.scala-sbt#main-settings;0.13.16!main-settings.jar (3810ms)
	[SUCCESSFUL ] org.scala-sbt#main;0.13.16!main.jar (4110ms)

:: problems summary ::
:::: WARNINGS
	problem while downloading module descriptor: https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/relation/0.13.16/ivys/ivy.xml: The HTTP response code for https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/relation/0.13.16/ivys/ivy.xml did not indicate a success. See log for more detail. (662ms)

		module not found: org.scala-sbt#relation;0.13.16

	==== local: tried

	  /Users/tisue/.ivy2/local/org.scala-sbt/relation/0.13.16/ivys/ivy.xml

	  -- artifact org.scala-sbt#relation;0.13.16!relation.jar:

	  /Users/tisue/.ivy2/local/org.scala-sbt/relation/0.13.16/jars/relation.jar

	==== Maven Central: tried

	  https://repo1.maven.org/maven2/org/scala-sbt/relation/0.13.16/relation-0.13.16.pom

	  -- artifact org.scala-sbt#relation;0.13.16!relation.jar:

	  https://repo1.maven.org/maven2/org/scala-sbt/relation/0.13.16/relation-0.13.16.jar

	==== sbt-maven-releases: tried

	  https://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/relation/0.13.16/relation-0.13.16.pom

	  -- artifact org.scala-sbt#relation;0.13.16!relation.jar:

	  https://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/relation/0.13.16/relation-0.13.16.jar

	==== sbt-maven-snapshots: tried

	  https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/scala-sbt/relation/0.13.16/relation-0.13.16.pom

	  -- artifact org.scala-sbt#relation;0.13.16!relation.jar:

	  https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/scala-sbt/relation/0.13.16/relation-0.13.16.jar

	==== typesafe-ivy-releases: tried

	  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/relation/0.13.16/ivys/ivy.xml

	==== sbt-ivy-snapshots: tried

	  https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/relation/0.13.16/ivys/ivy.xml

	problem while downloading module descriptor: https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-ivy-integration/0.13.16/ivys/ivy.xml: The HTTP response code for https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-ivy-integration/0.13.16/ivys/ivy.xml did not indicate a success. See log for more detail. (345ms)

		module not found: org.scala-sbt#compiler-ivy-integration;0.13.16

	==== local: tried

	  /Users/tisue/.ivy2/local/org.scala-sbt/compiler-ivy-integration/0.13.16/ivys/ivy.xml

	  -- artifact org.scala-sbt#compiler-ivy-integration;0.13.16!compiler-ivy-integration.jar:

	  /Users/tisue/.ivy2/local/org.scala-sbt/compiler-ivy-integration/0.13.16/jars/compiler-ivy-integration.jar

	==== Maven Central: tried

	  https://repo1.maven.org/maven2/org/scala-sbt/compiler-ivy-integration/0.13.16/compiler-ivy-integration-0.13.16.pom

	  -- artifact org.scala-sbt#compiler-ivy-integration;0.13.16!compiler-ivy-integration.jar:

	  https://repo1.maven.org/maven2/org/scala-sbt/compiler-ivy-integration/0.13.16/compiler-ivy-integration-0.13.16.jar

	==== sbt-maven-releases: tried

	  https://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/compiler-ivy-integration/0.13.16/compiler-ivy-integration-0.13.16.pom

	  -- artifact org.scala-sbt#compiler-ivy-integration;0.13.16!compiler-ivy-integration.jar:

	  https://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/compiler-ivy-integration/0.13.16/compiler-ivy-integration-0.13.16.jar

	==== sbt-maven-snapshots: tried

	  https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/scala-sbt/compiler-ivy-integration/0.13.16/compiler-ivy-integration-0.13.16.pom

	  -- artifact org.scala-sbt#compiler-ivy-integration;0.13.16!compiler-ivy-integration.jar:

	  https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/scala-sbt/compiler-ivy-integration/0.13.16/compiler-ivy-integration-0.13.16.jar

	==== typesafe-ivy-releases: tried

	  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-ivy-integration/0.13.16/ivys/ivy.xml

	==== sbt-ivy-snapshots: tried

	  https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/compiler-ivy-integration/0.13.16/ivys/ivy.xml

	problem while downloading module descriptor: https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/task-system/0.13.16/ivys/ivy.xml: The HTTP response code for https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/task-system/0.13.16/ivys/ivy.xml did not indicate a success. See log for more detail. (338ms)

		module not found: org.scala-sbt#task-system;0.13.16

	==== local: tried

	  /Users/tisue/.ivy2/local/org.scala-sbt/task-system/0.13.16/ivys/ivy.xml

	  -- artifact org.scala-sbt#task-system;0.13.16!task-system.jar:

	  /Users/tisue/.ivy2/local/org.scala-sbt/task-system/0.13.16/jars/task-system.jar

	==== Maven Central: tried

	  https://repo1.maven.org/maven2/org/scala-sbt/task-system/0.13.16/task-system-0.13.16.pom

	  -- artifact org.scala-sbt#task-system;0.13.16!task-system.jar:

	  https://repo1.maven.org/maven2/org/scala-sbt/task-system/0.13.16/task-system-0.13.16.jar

	==== sbt-maven-releases: tried

	  https://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/task-system/0.13.16/task-system-0.13.16.pom

	  -- artifact org.scala-sbt#task-system;0.13.16!task-system.jar:

	  https://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/task-system/0.13.16/task-system-0.13.16.jar

	==== sbt-maven-snapshots: tried

	  https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/scala-sbt/task-system/0.13.16/task-system-0.13.16.pom

	  -- artifact org.scala-sbt#task-system;0.13.16!task-system.jar:

	  https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/scala-sbt/task-system/0.13.16/task-system-0.13.16.jar

	==== typesafe-ivy-releases: tried

	  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/task-system/0.13.16/ivys/ivy.xml

	==== sbt-ivy-snapshots: tried

	  https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/task-system/0.13.16/ivys/ivy.xml

		module not found: org.scala-sbt#cache;0.13.16

	==== local: tried

	  /Users/tisue/.ivy2/local/org.scala-sbt/cache/0.13.16/ivys/ivy.xml

	  -- artifact org.scala-sbt#cache;0.13.16!cache.jar:

	  /Users/tisue/.ivy2/local/org.scala-sbt/cache/0.13.16/jars/cache.jar

	==== Maven Central: tried

	  https://repo1.maven.org/maven2/org/scala-sbt/cache/0.13.16/cache-0.13.16.pom

	  -- artifact org.scala-sbt#cache;0.13.16!cache.jar:

	  https://repo1.maven.org/maven2/org/scala-sbt/cache/0.13.16/cache-0.13.16.jar

	==== sbt-maven-releases: tried

	  https://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/cache/0.13.16/cache-0.13.16.pom

	  -- artifact org.scala-sbt#cache;0.13.16!cache.jar:

	  https://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/cache/0.13.16/cache-0.13.16.jar

	==== sbt-maven-snapshots: tried

	  https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/scala-sbt/cache/0.13.16/cache-0.13.16.pom

	  -- artifact org.scala-sbt#cache;0.13.16!cache.jar:

	  https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/scala-sbt/cache/0.13.16/cache-0.13.16.jar

	==== typesafe-ivy-releases: tried

	  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/cache/0.13.16/ivys/ivy.xml

	==== sbt-ivy-snapshots: tried

	  https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/cache/0.13.16/ivys/ivy.xml

		module not found: org.scala-sbt#testing;0.13.16

	==== local: tried

	  /Users/tisue/.ivy2/local/org.scala-sbt/testing/0.13.16/ivys/ivy.xml

	  -- artifact org.scala-sbt#testing;0.13.16!testing.jar:

	  /Users/tisue/.ivy2/local/org.scala-sbt/testing/0.13.16/jars/testing.jar

	==== Maven Central: tried

	  https://repo1.maven.org/maven2/org/scala-sbt/testing/0.13.16/testing-0.13.16.pom

	  -- artifact org.scala-sbt#testing;0.13.16!testing.jar:

	  https://repo1.maven.org/maven2/org/scala-sbt/testing/0.13.16/testing-0.13.16.jar

	==== sbt-maven-releases: tried

	  https://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/testing/0.13.16/testing-0.13.16.pom

	  -- artifact org.scala-sbt#testing;0.13.16!testing.jar:

	  https://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/testing/0.13.16/testing-0.13.16.jar

	==== sbt-maven-snapshots: tried

	  https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/scala-sbt/testing/0.13.16/testing-0.13.16.pom

	  -- artifact org.scala-sbt#testing;0.13.16!testing.jar:

	  https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/scala-sbt/testing/0.13.16/testing-0.13.16.jar

	==== typesafe-ivy-releases: tried

	  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/testing/0.13.16/ivys/ivy.xml

	==== sbt-ivy-snapshots: tried

	  https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/testing/0.13.16/ivys/ivy.xml

	problem while downloading module descriptor: https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/command/0.13.16/ivys/ivy.xml: The HTTP response code for https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/command/0.13.16/ivys/ivy.xml did not indicate a success. See log for more detail. (349ms)

		module not found: org.scala-sbt#command;0.13.16

	==== local: tried

	  /Users/tisue/.ivy2/local/org.scala-sbt/command/0.13.16/ivys/ivy.xml

	  -- artifact org.scala-sbt#command;0.13.16!command.jar:

	  /Users/tisue/.ivy2/local/org.scala-sbt/command/0.13.16/jars/command.jar

	==== Maven Central: tried

	  https://repo1.maven.org/maven2/org/scala-sbt/command/0.13.16/command-0.13.16.pom

	  -- artifact org.scala-sbt#command;0.13.16!command.jar:

	  https://repo1.maven.org/maven2/org/scala-sbt/command/0.13.16/command-0.13.16.jar

	==== sbt-maven-releases: tried

	  https://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/command/0.13.16/command-0.13.16.pom

	  -- artifact org.scala-sbt#command;0.13.16!command.jar:

	  https://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/command/0.13.16/command-0.13.16.jar

	==== sbt-maven-snapshots: tried

	  https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/scala-sbt/command/0.13.16/command-0.13.16.pom

	  -- artifact org.scala-sbt#command;0.13.16!command.jar:

	  https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/scala-sbt/command/0.13.16/command-0.13.16.jar

	==== typesafe-ivy-releases: tried

	  https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/command/0.13.16/ivys/ivy.xml

	==== sbt-ivy-snapshots: tried

	  https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/command/0.13.16/ivys/ivy.xml

		::::::::::::::::::::::::::::::::::::::::::::::

		::          UNRESOLVED DEPENDENCIES         ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: org.scala-sbt#relation;0.13.16: not found

		:: org.scala-sbt#compiler-ivy-integration;0.13.16: not found

		:: org.scala-sbt#task-system;0.13.16: not found

		:: org.scala-sbt#cache;0.13.16: not found

		:: org.scala-sbt#testing;0.13.16: not found

		:: org.scala-sbt#command;0.13.16: not found

		::::::::::::::::::::::::::::::::::::::::::::::


		::::::::::::::::::::::::::::::::::::::::::::::

		::              FAILED DOWNLOADS            ::

		:: ^ see resolution messages for details  ^ ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: org.scala-sbt#sbt;0.13.16!sbt.jar

		:: org.scala-sbt#io;0.13.16!io.jar

		:: org.scala-sbt#collections;0.13.16!collections.jar

		:: org.scala-sbt#api;0.13.16!api.jar

		:: org.scala-sbt#logging;0.13.16!logging.jar

		:: org.scala-sbt#process;0.13.16!process.jar

		:: org.scala-sbt#compile;0.13.16!compile.jar

		:: org.scala-sbt#cross;0.13.16!cross.jar

		:: org.scala-sbt#apply-macro;0.13.16!apply-macro.jar

		:: org.scala-sbt#logic;0.13.16!logic.jar

		:: org.scala-sbt#compiler-interface;0.13.16!compiler-interface.jar

		::::::::::::::::::::::::::::::::::::::::::::::



:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[error] [launcher] unresolved dependency: org.scala-sbt#relation;0.13.16: not found
[error] [launcher] unresolved dependency: org.scala-sbt#compiler-ivy-integration;0.13.16: not found
[error] [launcher] unresolved dependency: org.scala-sbt#task-system;0.13.16: not found
[error] [launcher] unresolved dependency: org.scala-sbt#cache;0.13.16: not found
[error] [launcher] unresolved dependency: org.scala-sbt#testing;0.13.16: not found
[error] [launcher] unresolved dependency: org.scala-sbt#command;0.13.16: not found
[error] [launcher] download failed: org.scala-sbt#sbt;0.13.16!sbt.jar
[error] [launcher] download failed: org.scala-sbt#io;0.13.16!io.jar
[error] [launcher] download failed: org.scala-sbt#collections;0.13.16!collections.jar
[error] [launcher] download failed: org.scala-sbt#api;0.13.16!api.jar
[error] [launcher] download failed: org.scala-sbt#logging;0.13.16!logging.jar
[error] [launcher] download failed: org.scala-sbt#process;0.13.16!process.jar
[error] [launcher] download failed: org.scala-sbt#compile;0.13.16!compile.jar
[error] [launcher] download failed: org.scala-sbt#cross;0.13.16!cross.jar
[error] [launcher] download failed: org.scala-sbt#apply-macro;0.13.16!apply-macro.jar
[error] [launcher] download failed: org.scala-sbt#logic;0.13.16!logic.jar
[error] [launcher] download failed: org.scala-sbt#compiler-interface;0.13.16!compiler-interface.jar
[error] [launcher] error during sbt launcher: error retrieving required libraries
  (see /Users/tisue/.sbt/boot/update.log for complete log)
[error] [launcher] could not retrieve sbt 0.13.16
```

**Comment by eed3si9n** [comment]
As far as I know Artsy the Artifactory instance is ok https://scala.jfrog.io/.

@SethTisue https://repo.typesafe.com/typesafe/ivy-releases/ seems to redirect https://dl.bintray.com/typesafe/ivy-releases/, which seems wrong? Given that https://github.com/sbt/sbt/blob/v1.9.9/launch/src/main/input_resources/sbt/sbt.boot.properties hasn't changed in 3 years, do you think something has changed in the redirect proxy recently?

**Comment by eed3si9n** [comment]
I don't know if the repo.typesafe.com situation is temporary or not, but here's a workaround that worked locally in a Docker container using https://www.scala-sbt.org/1.x/docs/Proxy-Repositories.html technique. Create a file at `$HOME/.sbt/repositories`:

```bash
[repositories]
  local
  maven-central
  old-sbt-ivy-releases: https://repo.scala-sbt.org/scalasbt/ivy-releases/, [organization]/[module]/[revision]/[type]s/[artifact](-[classifier]).[ext], bootOnly
```

Then invoke sbt with `-Dsbt.override.build.repos=true`:

```bash
[root@70657d6bd550 ~]# sbt -Dsbt.version=0.13.16 -Dsbt.override.build.repos=true
[info] Loading project definition from /root/project
[info] Set current project to root (in build file:/root/)
> compile
[success] Total time: 0 s, completed Apr 1, 2024 2:15:46 AM
```

**Comment by eed3si9n** [comment]
I actually get mix of both Artsy and Bintray:

```bash
[root@8e30e8e9ff63 ~]# curl -LI https://repo.typesafe.com/typesafe/ivy-releases/
HTTP/1.1 302 Moved Temporarily
Content-Length: 145
Content-Type: text/html
Date: Mon, 01 Apr 2024 02:31:27 GMT
Location: https://scala.jfrog.io/artifactory/ivy-releases/
Server: nginx/1.19.6
Connection: keep-alive

HTTP/1.1 200
Date: Mon, 01 Apr 2024 02:31:27 GMT
Content-Type: text/html
Connection: keep-alive
X-JFrog-Version: Artifactory/7.81.2 78102900
X-Artifactory-Id: 3371e186de962b7bc897d8402d319b9880ad66e8
X-Artifactory-Node-Id: scala-artifactory-primary-0
Access-Control-Allow-Methods: GET, POST, DELETE, PUT
Access-Control-Allow-Headers: X-Requested-With, Content-Type, X-Codingpedia
Cache-Control: no-store
X-Request-ID: 5987780e3350d8f25106657014ac7477

[root@8e30e8e9ff63 ~]# curl -LI https://repo.typesafe.com/typesafe/ivy-releases/
HTTP/1.1 302 Moved Temporarily
Content-Length: 145
Content-Type: text/html
Date: Mon, 01 Apr 2024 02:31:29 GMT
Location: https://dl.bintray.com/typesafe/ivy-releases/
Server: nginx/1.19.6
Connection: keep-alive

HTTP/1.1 404 Not Found
Date: Mon, 01 Apr 2024 02:31:29 GMT
Content-Type: text/html
Content-Length: 146
Connection: keep-alive
Strict-Transport-Security: max-age=31536000; includeSubDomains
```

**Comment by eed3si9n** [comment]
> ## expectation
>
> SBT 0.x works

While the current parties involved will likely try to resolve this issue, I should note that I **EOLed sbt 0.13.x on November 30, 2018** while I was at Lightbend (https://web.archive.org/web/20210918065807/https://www.lightbend.com/blog/scala-sbt-127-patchnotes):

> I would like to annouce the end of sbt 0.13 public support effective today

In other words, please adjust your expectation that at some point sbt 0.13 distribution might go away, and migrate to sbt 1.x.

**Comment by eed3si9n** [comment]
@JustinPihony confirmed that there was a issue with load balancer, and it's now fixed.

**Comment by MohammedAbadi1991** [comment]
@eed3si9n  the issue still exist , we are still facing the same issue

**Comment by eed3si9n** [comment]
@MohammedAbadi1991 what do you get for `curl -LI https://repo.typesafe.com/typesafe/ivy-releases/`?

Also maybe it takes a few hours to a day for DNS to propagate everywhere, so maybe check back in a few hours again?

**Comment by MohammedAbadi1991** [comment]
@eed3si9n  I am getting the following : 
```bash
HTTP/1.1 302 Moved Temporarily
Content-Length: 145
Content-Type: text/html
Date: Mon, 01 Apr 2024 16:34:20 GMT
Location: https://dl.bintray.com/typesafe/ivy-releases/
Server: nginx/1.19.6
Connection: keep-alive

HTTP/1.1 404 Not Found
Date: Mon, 01 Apr 2024 16:34:21 GMT
Content-Type: text/html
Content-Length: 146
Connection: keep-alive
Strict-Transport-Security: max-age=31536000; includeSubDomains
```

**Comment by eed3si9n** [comment]
For the record, here's `dig repo.typesafe.com` that I get currently:

```bash
$ dig repo.typesafe.com

; <<>> DiG 9.10.6 <<>> repo.typesafe.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 22323
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;repo.typesafe.com.		IN	A

;; ANSWER SECTION:
repo.typesafe.com.	79990	IN	CNAME	resolver-nginx-redirect-lb-new-1947871190.us-east-1.elb.amazonaws.com.
resolver-nginx-redirect-lb-new-1947871190.us-east-1.elb.amazonaws.com. 60 IN A 34.225.59.228
resolver-nginx-redirect-lb-new-1947871190.us-east-1.elb.amazonaws.com. 60 IN A 54.90.3.238
```

**Comment by JustinPihony** [comment]
It indeed has a 1 day TTL. If you are blocked you can temporarily point to https://scala.jfrog.io/artifactory/ivy-releases/

**Comment by SethTisue** [comment]
Thanks Justin & Eugene ❤️

**Comment by MohammedAbadi1991** [comment]
Issue resolved now , thanks @eed3si9n !

**Comment by eed3si9n** [comment]
ok. Closing this.

**Comment by ntnvi10** [comment]
Hey @eed3si9n @SethTisue , sorry to bug you on this, but my jenkins job is still throwing error downloading the dependencies

`[FAILED     ] org.scala-sbt#apply-macro;0.13.16!apply-macro.jar: The HTTP response code for https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/apply-macro/0.13.16/jars/apply-macro.jar did not indicate a success. See log for more detail. (105ms)`

similar error for multiple dependencies

`::::::::::::::::::::::::::::::::::::::::::::::

		::          UNRESOLVED DEPENDENCIES         ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: org.scala-sbt#incremental-compiler;0.13.16: not found

		:: org.scala-sbt#compile;0.13.16: not found

		:: org.scala-sbt#persist;0.13.16: not found

		:: org.scala-sbt#cross;0.13.16: not found

		:: org.scala-sbt#run;0.13.16: not found

		:: org.scala-sbt#relation;0.13.16: not found

		:: org.scala-sbt#task-system;0.13.16: not found

		:: org.scala-sbt#tasks;0.13.16: not found

		:: org.scala-sbt#tracking;0.13.16: not found

		:: org.scala-sbt#compiler-interface;0.13.16: not found`

**Comment by MohammedAbadi1991** [comment]
@ntnvi10  it will take up to 24 hours , in my case I am in a different region
