### ISSUE TITLE
Editing shortcuts do not work in sbt 0.13 under cygwin

### ISSUE THREAD

**Issue by OlegYch** [sbt/sbt#763]
I have a script like this

``` bash
#!/bin/bash
SCRIPT_PATH="${BASH_SOURCE[0]}";
if([ -h "${SCRIPT_PATH}" ]) then
  while([ -h "${SCRIPT_PATH}" ]) do SCRIPT_PATH=`readlink "${SCRIPT_PATH}"`; done
fi
pushd . > /dev/null
cd "`dirname "${SCRIPT_PATH}"`" > /dev/null
SCRIPT_PATH=`pwd`;
popd  > /dev/null

script_dir=`cygpath -w "${SCRIPT_PATH}" || echo "${SCRIPT_PATH}"`

java -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256m -Dfile.encoding=utf-8 $SBT_OPTS -jar "$script_dir/sbt-launcher/xsbt-launch.jar" "$@"
```

to launch sbt > 0.10

Under windows 8 with cygwin editing text in sbt shell does not work:
http://gyazo.com/1640d1e844b82670ccf93c6eea3a9136.png

Instead of left-right-up-down shortcuts i get weird characters printed.

**Comment by harrah** [comment]
JLine fixes are a priority before RC1.  I'm just not sure whether I'll try to fix this before or after the Beta (which should be soon).

**Comment by harrah** [comment]
Possibly fixed by 1a3ea6fb8b73d290aab73964c62ad3b14c30916b.  Related to #562.

**Comment by OlegYch** [comment]
the issue still exists in http://repo.typesafe.com/typesafe/ivy-snapshots/org.scala-sbt/sbt-launch/0.13.0-20130622-143830/sbt-launch.jar

**Comment by jsuereth** [comment]
I believe you also need:  -Djline.terminal=jline.UnixTerminal to get full
cygwin support, along with some STTY magic around the edges...

**Comment by OlegYch** [comment]
Thanks Josh! That almost fixes it. The only missing bit is tab completion.
Btw shortcuts/tab completion do not work in plain cmd either  (unless i add -Djline.terminal=none or -Djline.terminal=jline.UnixTerminal)

**Comment by OlegYch** [comment]
Note that tab completion works if i don't specify jline.terminal

**Comment by jsuereth** [comment]
Hmm...  I know jline.UnixTerminal tries to use stty, so we have this hack
in our scripts:
https://github.com/sbt/sbt-launcher-package/blob/feature/windows-sbt-config/src/windows/sbt#L18

I'm trying to find a good workaround so everything works in cygwin with the
least amount of fuss.  I'll be diving in a bit more on monday.  Do you have
any thoughts on how to make jline aware of Cygwin's stty command?

**Comment by OlegYch** [comment]
I'm not sure if this is related to cygwin as i get exactly the same behavior in cmd and cygwin bash. I.e. tab works only with WindowsTerminal while other shortcuts work only with UnixTerminal.

**Comment by OlegYch** [comment]
One more bug with UnixTerminal - it prints sbt prompt (> ) twice.

**Comment by OlegYch** [comment]
hm i tried 0.13.0-20130627-052237 (launcher and sbt) but that doesn't seem to change anything even with -Dsbt.cygwin=true

**Comment by harrah** [comment]
That would be surprising, since I tested cygwin with both mintty and some other terminal I'll have to look up.  Note that you still need -Djline.terminal=UnixTerminal as well.  Can you post your command line and the specific issues remaining (unless everything is broken).

**Comment by OlegYch** [comment]
So far i've tried plain cmd, and cygwin bash from cmd - the behavior is the same. I get the same behavior with tcc/le and bash in ConEmu as well. Haven't tried mintty. Btw console task seems to be fine if i set terminal to Windows.

Here are a few screenshots
http://gyazo.com/88a84119f92294522fc069f5496e5977.png
http://gyazo.com/9ff5aa679d2974f754fb987058e43443.png
http://gyazo.com/a2361ca98f283d62b941bc5e75fe01f2.png

**Comment by harrah** [comment]
So, "cygwin" is something of an inaccurate term.  It really means "terminal that understands ansi escape codes".  If you are using plain cmd, don't set either `jline.terminal` or `sbt.cygwin` and it will use a native library to provide the color support.  I'm not sure what name should replace this ambiguous use of "cygwin".

**Comment by harrah** [comment]
As @jsuereth clarified, cygwin is still a relevant distinction since it is necessary to set up the terminal correctly with stty.

**Comment by OlegYch** [comment]
I don't really care about color support. 
So far i was trying to get basic text editing and tab completion working (it doesn't work in both cmd and bash currently).

**Comment by harrah** [comment]
If using cygwin+a terminal that supports ansi escape sequences (like mintty), `-Djline.terminal=UnixTerminal -Dsbt.cygwin=true`.  If not, add nothing.  `WindowsTerminal` should be automatically selected if nothing is explicitly added.

**Comment by OlegYch** [comment]
left-right-up-down shortcuts still do not work http://gyazo.com/ae52abfad4f48d9ee7983ee3fd3eb6d2.png

**Comment by OlegYch** [comment]
I just tried http://scalasbt.artifactoryonline.com/scalasbt/sbt-native-packages/org/scala-sbt/sbt/0.13.0-RC2/sbt.msi and http://scalasbt.artifactoryonline.com/scalasbt/sbt-native-packages/org/scala-sbt/sbt/0.13.0-RC2/sbt.zip
in plain cmd.exe and i still can't edit text. How did you guys test it?

**Comment by jsuereth** [comment]
I install it on my local machine and run through my normal sbt dev
experience and see if it works.

If you have a script of what you do, I'll start following that for
validation.

**Comment by OlegYch** [comment]
I don't do anything special..
Just verified on a clean win8 vm. Installed oracle jre and 0.13.0-RC2 msi and started a clean project.
Still getting pH instead of Up key in sbt shell...
http://gyazo.com/21d02544b5be51043dfa52d419a8ce36.png

btw the msi contains some ~ files (i guess backups from your editor) and "sbt" script breaks in cygwin bash when started from directory with spaces in path.

**Comment by jsuereth** [comment]
Thanks, can you open these bugs against the sbt-launcher package?

https://github.com/sbt/sbt-launcher-package/issues/new

**Comment by OlegYch** [comment]
sure, submitted https://github.com/sbt/sbt-launcher-package/issues/50 and https://github.com/sbt/sbt-launcher-package/issues/49
